/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","az",{title:"?lill?r? d?st?k üzr? t?limat",contents:"Köm?k. P?nc?r?ni baglamaq üçün ESC basin.",legend:[{name:"?sas",items:[{name:"Düz?lis ed?nin al?tl?r çubugu",legend:"Panel? keçm?k üçün ${toolbarFocus} basin. Növb?ti panel? TAB, ?vv?lki panel? is? SHIFT+TAB düym?si vasit?si il? keç? bil?rsiz. Paneld?ki düym?l?r arasinda sol v? sag ox düym?si il? keçid ed? bil?rsiz. Seçilmis düym?si SPACE v? ya ENTER il? isl?d? bil?rsiniz."},{name:"Redaktorun p?nc?r?si",legend:"P?nc?r? içind? növb?ti element seçm?k üçün TAB düym?ni basin, ?vv?lki is? - SHIFT+TAB. T?sdiq edilm?si üçün ENTER, imtina edilm?si is? ESC diym?l?ri istifad? edin. P?nc?r?d? bir neç? v?r?q olanda olnarin siyahi ALT+F10 il? aça bil?rsiz. V?r?ql?rin siyahi fokus altinda olanda ox düym?l?r vasit?si il? onlarin arasinda keçid ed? bil?rsiz."},
{name:"Redaktorun seçiml?rin menyusu",legend:"Seçiml?ri redakt? etm?k üçün ${contextMenu} ya da APPLICATION KEY basin. Növb?ti seçim? keçm?k üçün TAB ya ASAGI OX düym?sini basin, ?vv?lki is? - SHIFT+TAB ya YUXARI OX. Seçimi arimaq SPACE ya ENTER düym?l?ri istifad? edin. Alt menyunu açmaq üçün SPACE, ENTER ya SAGA OX basin. ESC ya SOLA OX il? geriy? qayida bil?rsiz. Bütün menyunu ESC il? bagliyin."},{name:"Düz?lis ed?nin siyahi qutusu",legend:"Siyahi qutusu içind? növb?ti b?nd seçm?k üçün TAB ya ASAGI OX, ?vv?lki is? SHIFT+TAB ya YUXARI OX basin. Seçimi arimaq SPACE ya ENTER düym?l?ri istifad? edin. Siyahi qutusu ESC il? bagliyin."},
{name:"Redaktor elementin cigir paneli",legend:"Elementin cigir paneli seçm?k üçün ${elementsPathFocus} basin. Növb?ti element seçm?k üçün TAB ya SAGA OX, ?vv?lki is? SHIFT+TAB ya SOLA OX istifad? edin. Elementi arimaq SPACE ya ENTER düym?l?ri mövcuddur."}]},{name:"?mrl?r",items:[{name:"?mri geri qaytar",legend:"${undo} basin"},{name:"Geri ?mri",legend:"${redo} basin"},{name:"Qalin ?mri",legend:"${bold}  basin"},{name:"Kursiv ?mri",legend:"${italic} basin"},{name:"Altdan x?tt ?mri",legend:"${underline} basin"},
{name:"Link ?mri",legend:"${link} basin"},{name:"Paneli gizl?t ?mri",legend:"${toolbarCollapse} basin"},{name:"?vv?lki fokus sah?si seç ?mri",legend:"Kursordan ?vv?l ?n yaxin ?lçatmaz yer? d?ym?k üçün ${accessPreviousSpace} basin, misal üçün: iki dal-badal HR teg. Uzaq yerl?r? d?ym?k üçün bir neç? d?f? basin."},{name:"Növb?ti fokus sah?si seç ?mri",legend:"Kursordan sonra ?n yaxin ?lçatmaz yer? d?ym?k üçün ${accessNextSpace} basin, misal üçün: iki dal-badal HR teg. Uzaq yerl?r? d?ym?k üçün bir neç? d?f? basin."},
{name:"H?rt?r?fli Köm?k",legend:"${a11yHelp} basin"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Sola ox isar?si",upArrow:"Yuxari ox isar?si",rightArrow:"Saga ox isar?si",downArrow:"Asagi ox isar?si",insert:"Insert",leftWindowKey:"Soldaki Windows düym?si",rightWindowKey:"Sagdaki Windows düym?si",selectKey:"Düym?ni seçin",
numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Vurma",add:"?lav? et",subtract:"Çixma",decimalPoint:"Onluq k?sri tam ?d?dd?n ayiran nöqt?",divide:"Bölüsdürm?",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Nöqt?li verqül",equalSign:"Bar?b?rlik isar?si",
comma:"Vergül",dash:"Defis",period:"Nöqt?",forwardSlash:"Ç?p x?tt",graveAccent:"Vurgu isar?si",openBracket:"Açilan möt?riz?",backSlash:"T?rs ç?p?ki x?tt",closeBracket:"Baglanan möt?riz?",singleQuote:"T?k dirnaq"});
