/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","cs",{title:"Instrukce pro prístupnost",contents:"Obsah nápovedy. Pro uzavrení tohoto dialogu stisknete klávesu ESC.",legend:[{name:"Obecné",items:[{name:"Panel nástroju editoru",legend:"Stisknete${toolbarFocus} k procházení panelu nástroju. Prejdete na další a predchozí skupiny pomocí TAB a SHIFT+TAB. Prechod na další a predchozí tlacítko panelu nástroju je pomocí ŠIPKA VPRAVO nebo ŠIPKA VLEVO. Stisknutím mezerníku nebo klávesy ENTER tlacítko aktivujete."},{name:"Dialogové okno editoru",
legend:"Uvnitr dialogového okna stisknete TAB pro presunutí na další prvek okna, stisknete SHIFT+TAB pro presun na predchozí prvek okna, stisknete ENTER pro odeslání dialogu, stisknete ESC pro jeho zrušení. Pro dialogová okna, která mají mnoho karet stisknete ALT+F10 pro zamerení seznamu karet, nebo TAB, pro posun podle poradí karet.Pri zamerení seznamu karet se mužete jimi posouvat pomocí ŠIPKY VPRAVO a VLEVO."},{name:"Kontextové menu editoru",legend:"Stisknete ${contextMenu} nebo klávesu APPLICATION k otevrení kontextového menu. Pak se presunte na další možnost menu pomocí TAB nebo ŠIPKY DOLU. Presunte se na predchozí možnost pomocí  SHIFT+TAB nebo ŠIPKY NAHORU. Stisknete MEZERNÍK nebo ENTER pro zvolení možnosti menu. Podmenu soucasné možnosti otevrete pomocí MEZERNÍKU nebo ENTER ci ŠIPKY DOLEVA. Kontextové menu uzavrete stiskem ESC."},
{name:"Rámecek seznamu editoru",legend:"Uvnitr rámecku seznamu se presunete na další položku menu pomocí TAB nebo ŠIPKA DOLU. Na predchozí položku se presunete SHIFT+TAB nebo ŠIPKA NAHORU. Stisknete MEZERNÍK nebo ENTER pro zvolení možnosti seznamu. Stisknete ESC pro uzavrení seznamu."},{name:"Lišta cesty prvku v editoru",legend:"Stisknete ${elementsPathFocus} pro procházení lišty cesty prvku. Na další tlacítko prvku se presunete pomocí TAB nebo ŠIPKA VPRAVO. Na predchozí tlacítko se presunete pomocí SHIFT+TAB nebo ŠIPKA VLEVO. Stisknete MEZERNÍK nebo ENTER pro vybrání prvku v editoru."}]},
{name:"Príkazy",items:[{name:" Príkaz Zpet",legend:"Stisknete ${undo}"},{name:" Príkaz Znovu",legend:"Stisknete ${redo}"},{name:" Príkaz Tucné",legend:"Stisknete ${bold}"},{name:" Príkaz Kurzíva",legend:"Stisknete ${italic}"},{name:" Príkaz Podtržení",legend:"Stisknete ${underline}"},{name:" Príkaz Odkaz",legend:"Stisknete ${link}"},{name:" Príkaz Skrýt panel nástroju",legend:"Stisknete ${toolbarCollapse}"},{name:"Príkaz pro prístup k predchozímu prostoru zamerení",legend:"Stisknete ${accessPreviousSpace} pro prístup k nejbližšímu nedosažitelnému prostoru zamerení pred stríškou, napríklad: dva prilehlé prvky HR. Pro dosažení vzdálených prostoru zamerení tuto kombinaci kláves opakujte."},
{name:"Príkaz pro prístup k dalšímu prostoru zamerení",legend:"Stisknete ${accessNextSpace} pro prístup k nejbližšímu nedosažitelnému prostoru zamerení po stríšce, napríklad: dva prilehlé prvky HR. Pro dosažení vzdálených prostoru zamerení tuto kombinaci kláves opakujte."},{name:" Nápoveda prístupnosti",legend:"Stisknete ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tabulátor",pause:"Pauza",capslock:"Caps lock",
escape:"Escape",pageUp:"Stránka nahoru",pageDown:"Stránka dolu",leftArrow:"Šipka vlevo",upArrow:"Šipka nahoru",rightArrow:"Šipka vpravo",downArrow:"Šipka dolu",insert:"Vložit",leftWindowKey:"Levá klávesa Windows",rightWindowKey:"Pravá klávesa Windows",selectKey:"Vyberte klávesu",numpad0:"Numerická klávesa 0",numpad1:"Numerická klávesa 1",numpad2:"Numerická klávesa 2",numpad3:"Numerická klávesa 3",numpad4:"Numerická klávesa 4",numpad5:"Numerická klávesa 5",numpad6:"Numerická klávesa 6",numpad7:"Numerická klávesa 7",
numpad8:"Numerická klávesa 8",numpad9:"Numerická klávesa 9",multiply:"Numerická klávesa násobení",add:"Pridat",subtract:"Numerická klávesa odecítání",decimalPoint:"Desetinná tecka",divide:"Numerická klávesa delení",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num lock",scrollLock:"Scroll lock",semiColon:"Stredník",equalSign:"Rovnítko",comma:"Cárka",dash:"Pomlcka",period:"Tecka",forwardSlash:"Lomítko",graveAccent:"Prízvuk",openBracket:"Otevrená hranatá závorka",
backSlash:"Obrácené lomítko",closeBracket:"Uzavrená hranatá závorka",singleQuote:"Jednoduchá uvozovka"});
