/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","hu",{title:"Kisegíto utasítások",contents:"Súgó tartalmak. A párbeszédablak bezárásához nyomjon ESC-et.",legend:[{name:"Általános",items:[{name:"Szerkeszto Eszköztár",legend:"Nyomjon ${toolbarFocus} hogy kijelölje az eszköztárat. A következo és elozo eszköztár csoporthoz a TAB és SHIFT+TAB-al juthat el. A következo és elozo eszköztár gombhoz a BAL NYÍL vagy JOBB NYÍL gombbal juthat el. Nyomjon SPACE-t vagy ENTER-t hogy aktiválja az eszköztár gombot."},{name:"Szerkeszo párbeszéd ablak",
legend:"Párbeszédablakban nyomjon TAB-ot a következo párbeszédmezohöz ugráshoz, nyomjon SHIFT + TAB-ot az elozo mezohöz ugráshoz, nyomjon ENTER-t a párbeszédablak elfogadásához, nyomjon ESC-et a párbeszédablak elvetéséhez. Azokhoz a párbeszédablakokhoz, amik több fület tartalmaznak, nyomjon ALT + F10-et vagy TAB-ot hogy a fülekre ugorjon. Ezután a TAB-al vagy a JOBB NYÍLLAL a következo fülre ugorhat."},{name:"Szerkeszto helyi menü",legend:"Nyomjon ${contextMenu}-t vagy ALKALMAZÁS BILLENTYUT a helyi menü megnyitásához. Ezután a következo menüpontra léphet a TAB vagy LEFELÉ NYÍLLAL. Az elozo opciót a SHIFT+TAB vagy FELFELÉ NYÍLLAL érheti el. Nyomjon SPACE-t vagy ENTER-t a menüpont kiválasztásához. A jelenlegi menüpont almenüjének megnyitásához nyomjon SPACE-t vagy ENTER-t, vagy JOBB NYILAT. A fomenühöz való visszatéréshez nyomjon ESC-et vagy BAL NYILAT. A helyi menü bezárása az ESC billentyuvel lehetséges."},
{name:"Szerkeszto lista",legend:"A listán belül a következo elemre a TAB vagy LEFELÉ NYÍLLAL mozoghat. Az elozo elem kiválasztásához nyomjon SHIFT+TAB-ot vagy FELFELÉ NYILAT. Nyomjon SPACE-t vagy ENTER-t az elem kiválasztásához. Az ESC billentyu megnyomásával bezárhatja a listát."},{name:"Szerkeszto elem utak sáv",legend:"Nyomj ${elementsPathFocus} hogy kijelöld a elemek út sávját. A következo elem gombhoz a TAB-al vagy a JOBB NYÍLLAL juthatsz el. Az elozo gombhoz a SHIFT+TAB vagy BAL NYÍLLAL mehetsz. A SPACE vagy ENTER billentyuvel kiválaszthatod az elemet a szerkesztoben."}]},
{name:"Parancsok",items:[{name:"Parancs visszavonása",legend:"Nyomj ${undo}"},{name:"Parancs megismétlése",legend:"Nyomjon ${redo}"},{name:"Félkövér parancs",legend:"Nyomjon ${bold}"},{name:"Dolt parancs",legend:"Nyomjon ${italic}"},{name:"Aláhúzott parancs",legend:"Nyomjon ${underline}"},{name:"Link parancs",legend:"Nyomjon ${link}"},{name:"Szerkesztosáv összecsukása parancs",legend:"Nyomjon ${toolbarCollapse}"},{name:"Hozzáférés az elozo fókusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzáférj a legközelebbi elérhetetlen fókusz helyhez a hiányjel elott, például: két szomszédos HR elemhez. Ismételd meg a billentyukombinációt hogy megtaláld a távolabbi fókusz helyeket."},
{name:"Hozzáférés a következo fókusz helyhez parancs",legend:"Nyomj ${accessNextSpace} hogy hozzáférj a legközelebbi elérhetetlen fókusz helyhez a hiányjel után, például: két szomszédos HR elemhez. Ismételd meg a billentyukombinációt hogy megtaláld a távolabbi fókusz helyeket."},{name:"Kisegíto súgó",legend:"Nyomjon ${a11yHelp}"},{name:"Beillesztés egyszeru szövegként",legend:"Nyomd meg: ${pastetext}",legendEdge:"Nyomj ${pastetext}, majd ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",
escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"balra nyíl",upArrow:"felfelé nyíl",rightArrow:"jobbra nyíl",downArrow:"lefelé nyíl",insert:"Insert",leftWindowKey:"bal Windows-billentyu",rightWindowKey:"jobb Windows-billentyu",selectKey:"Billentyu választása",numpad0:"Számbillentyuk 0",numpad1:"Számbillentyuk 1",numpad2:"Számbillentyuk 2",numpad3:"Számbillentyuk 3",numpad4:"Számbillentyuk 4",numpad5:"Számbillentyuk 5",numpad6:"Számbillentyuk 6",numpad7:"Számbillentyuk 7",numpad8:"Számbillentyuk 8",
numpad9:"Számbillentyuk 9",multiply:"Szorzás",add:"Hozzáadás",subtract:"Kivonás",decimalPoint:"Tizedespont",divide:"Osztás",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Pontosvesszo",equalSign:"Egyenloségjel",comma:"Vesszo",dash:"Kötojel",period:"Pont",forwardSlash:"Perjel",graveAccent:"Visszafelé dolo ékezet",openBracket:"Nyitó szögletes zárójel",backSlash:"fordított perjel",closeBracket:"Záró szögletes zárójel",
singleQuote:"szimpla idézojel"});
