/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","lv",{title:"Pieejamibas instrukcija",contents:"Palidzibas saturs. Lai aizvertu ciet šo dialogu nospiediet ESC.",legend:[{name:"Galvenais",items:[{name:"Redaktora rikjosla",legend:"Nospiediet ${toolbarFocus} lai parvietotos uz rikjoslu. Lai parvietotos uz nakošo vai iepriekšejo rikjoslas grupu izmantojiet pogu TAB un SHIFT+TAB. Lai parvietotos uz nakošo vai iepriekšejo rikjoslas pogu izmantojiet Kreiso vai Labo bultinu. Nospiediet Atstarpi vai ENTER lai aktivizetu rikjosla pogu."},
{name:"Redaktora dialoga  logs",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},{name:"Redaktora satura izvele",legend:"Nospiediet ${contextMenu} vai APPLICATION KEY lai atvertu satura izvelni. Lai parvietotos uz nakošo izvelnes opciju izmantojiet pogu TAB vai pogu Bultinu uz leju. Lai parvietotos uz iepriekšejo opciju izmantojiet  SHIFT+TAB vai pogu Bultina uz augšu. Nospiediet SPACE vai ENTER lai izveletos izvelnes opciju. Atveriet tekošaja opcija apakšizvelni ar SAPCE vai ENTER ka ari to var izdarit ar Labo bultinu. Lai atgrieztos atpakal uz sakuma izvelni nospiediet ESC vai Kreiso bultinu. Lai aizvertu ciet izvelnes saturu nospiediet ESC."},
{name:"Redaktora saraksta lauks",legend:"Saraksta lauka, lai parvietotos uz nakošo saraksta elementu nospiediet TAB vai pogu Bultina uz leju. Lai parvietotos uz iepriekšejo saraksta elementu nospiediet SHIFT+TAB vai pogu Bultina uz augšu. Nospiediet SPACE vai ENTER lai izveletos saraksta opcijas. Nospiediet ESC lai aizvertu saraksta lauku."},{name:"Redaktora elementa cela josla",legend:"Nospiediet ${elementsPathFocus} lai parvietotos uz elementa cela joslu. Lai parvietotos uz nakošo elementa pogu izmantojiet TAB vai Labo bultinu. Lai parvietotos uz iepriekšejo elementa pogu izmantojiet SHIFT+TAB vai Kreiso bultinu. Nospiediet SPACE vai ENTER lai izveletos elementu redaktora."}]},
{name:"Komandas",items:[{name:"Komanda atcelt darbibu",legend:"Nospiediet ${undo}"},{name:"Komanda atkartot darbibu",legend:"Nospiediet ${redo}"},{name:"Treknraksta komanda",legend:"Nospiediet ${bold}"},{name:"Kursiva komanda",legend:"Nospiediet ${italic}"},{name:"Apakšsvitras komanda ",legend:"Nospiediet ${underline}"},{name:"Hipersaites komanda",legend:"Nospiediet ${link}"},{name:"Rikjoslas aizveršanas komanda",legend:"Nospiediet ${toolbarCollapse}"},{name:"Pieklut iepriekšejai fokusa vietas komandai",
legend:"Nospiediet ${accessPreviousSpace} lai pieklutu tuvakajai nepieejamajai fokusa vietai pirms kursora. Piemeram: diviem blakus esošiem linijas HR elementiem. Atkartojiet taustinu kombinaciju lai pieklutu pie talakam vietam."},{name:"Pieklut nakoša fokusa apgabala komandai",legend:"Nospiediet ${accessNextSpace} lai pieklutu tuvakajai nepieejamajai fokusa vietai pec kursora. Piemeram: diviem blakus esošiem linijas HR elementiem. Atkartojiet taustinu kombinaciju lai pieklutu pie talakam vietam."},
{name:"Pieejamibas palidziba",legend:"Nospiediet ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Left Arrow",upArrow:"Up Arrow",rightArrow:"Right Arrow",downArrow:"Down Arrow",insert:"Insert",leftWindowKey:"Left Windows key",rightWindowKey:"Right Windows key",selectKey:"Select key",numpad0:"Numpad 0",numpad1:"Numpad 1",
numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Multiply",add:"Add",subtract:"Subtract",decimalPoint:"Decimal Point",divide:"Divide",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Semicolon",equalSign:"Equal Sign",comma:"Comma",dash:"Dash",period:"Period",forwardSlash:"Forward Slash",
graveAccent:"Grave Accent",openBracket:"Open Bracket",backSlash:"Backslash",closeBracket:"Close Bracket",singleQuote:"Single Quote"});
