/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","pl",{title:"Instrukcje dotyczace dostepnosci",contents:"Zawartosc pomocy. Wcisnij ESC, aby zamknac to okno.",legend:[{name:"Informacje ogólne",items:[{name:"Pasek narzedzi edytora",legend:"Nacisnij ${toolbarFocus}, by przejsc do paska narzedzi. Przejdz do nastepnej i poprzedniej grupy narzedzi uzywajac TAB oraz SHIFT+TAB. Przejdz do nastepnego i poprzedniego przycisku paska narzedzi za pomoca STRZALKI W PRAWO lub STRZALKI W LEWO. Nacisnij SPACJE lub ENTER by aktywowac przycisk paska narzedzi."},
{name:"Okno dialogowe edytora",legend:"Wewnatrz okna dialogowego nacisnij TAB, by przejsc do kolejnego elementu tego okna lub SHIFT+TAB, by przejsc do poprzedniego elementu okna. Nacisnij ENTER w celu zatwierdzenia opcji okna dialogowego lub ESC w celu anulowania zmian. Jesli okno dialogowe ma kilka zakladek, do listy zakladek mozna przejsc za pomoca ALT+F10 lub TAB. Gdy lista zakladek jest aktywna, mozesz przejsc do kolejnej i poprzedniej zakladki za pomoca STRZALKI W PRAWO i STRZALKI W LEWO."},
{name:"Menu kontekstowe edytora",legend:"Wcisnij ${contextMenu} lub PRZYCISK APLIKACJI aby otworzyc menu kontekstowe. Przejdz do nastepnej pozycji menu wciskajac TAB lub STRZALKE W DÓL. Przejdz do poprzedniej pozycji menu wciskajac SHIFT + TAB lub STRZALKE W GÓRE. Wcisnij SPACJE lub ENTER aby wygrac pozycje menu. Otwórz pod-menu obecnej pozycji wciskajac SPACJE lub ENTER lub STRZALKE W PRAWO. Wróc do pozycji nadrzednego menu wciskajac ESC lub STRZALKE W LEWO. Zamknij menu wciskajac ESC."},{name:"Lista w edytorze",
legend:"Wewnatrz listy przejdz do kolejnego elementu listy za pomoca przycisku TAB lub STRZALKI W DÓL. Przejdz do poprzedniego elementu listy za pomoca SHIFT+TAB lub STRZALKI W GÓRE. Nacisnij SPACJE lub ENTER w celu wybrania opcji z listy. Nacisnij ESC, by zamknac liste."},{name:"Pasek sciezki elementów edytora",legend:"Nacisnij ${elementsPathFocus} w celu przejscia do paska sciezki elementów edytora. W celu przejscia do kolejnego elementu nacisnij klawisz TAB lub STRZALKI W PRAWO. W celu przejscia do poprzedniego elementu nacisnij klawisze SHIFT+TAB lub STRZALKI W LEWO. By wybrac element w edytorze, uzyj klawisza SPACJI lub ENTER."}]},
{name:"Polecenia",items:[{name:"Polecenie Cofnij",legend:"Nacisnij ${undo}"},{name:"Polecenie Ponów",legend:"Nacisnij ${redo}"},{name:"Polecenie Pogrubienie",legend:"Nacisnij ${bold}"},{name:"Polecenie Kursywa",legend:"Nacisnij ${italic}"},{name:"Polecenie Podkreslenie",legend:"Nacisnij ${underline}"},{name:"Polecenie Wstaw/ edytuj odnosnik",legend:"Nacisnij ${link}"},{name:"Polecenie schowaj pasek narzedzi",legend:"Nacisnij ${toolbarCollapse}"},{name:"Przejdz do poprzedniego miejsca, w którym mozna ustawic focus",
legend:"Nacisnij ${accessPreviousSpace}, aby przejsc do najblizszego niedostepnego miejsca przed kursorem, w którym mozna ustawic focus. Przyklad: dwa przylegajace elementy HR. Powtórz ten skrót klawiaturowy, by dotrzec do kolejnych takich miejsc."},{name:"Przejdz do nastepnego miejsca, w którym mozna ustawic focus",legend:"Nacisnij ${accessNextSpace}, aby przejsc do najblizszego niedostepnego miejsca po kursorze, w którym mozna ustawic focus. Przyklad: dwa przylegajace elementy HR. Powtórz ten skrót klawiaturowy, by dotrzec do kolejnych takich miejsc."},
{name:"Pomoc dotyczaca dostepnosci",legend:"Nacisnij ${a11yHelp}"},{name:"Wklej jako tekst",legend:"Nacisnij ${pastetext}",legendEdge:"Nacisnij ${pastetext}, a nastepnie ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Page Up",pageDown:"Page Down",leftArrow:"Strzalka w lewo",upArrow:"Strzalka w góre",rightArrow:"Strzalka w prawo",downArrow:"Strzalka w dól",insert:"Insert",leftWindowKey:"Lewy klawisz Windows",rightWindowKey:"Prawy klawisz Windows",selectKey:"Klawisz wyboru",
numpad0:"Klawisz 0 na klawiaturze numerycznej",numpad1:"Klawisz 1 na klawiaturze numerycznej",numpad2:"Klawisz 2 na klawiaturze numerycznej",numpad3:"Klawisz 3 na klawiaturze numerycznej",numpad4:"Klawisz 4 na klawiaturze numerycznej",numpad5:"Klawisz 5 na klawiaturze numerycznej",numpad6:"Klawisz 6 na klawiaturze numerycznej",numpad7:"Klawisz 7 na klawiaturze numerycznej",numpad8:"Klawisz 8 na klawiaturze numerycznej",numpad9:"Klawisz 9 na klawiaturze numerycznej",multiply:"Przemnóz",add:"Plus",
subtract:"Minus",decimalPoint:"Separator dziesietny",divide:"Podziel",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Srednik",equalSign:"Znak równosci",comma:"Przecinek",dash:"Pauza",period:"Kropka",forwardSlash:"Ukosnik prawy",graveAccent:"Akcent slaby",openBracket:"Nawias kwadratowy otwierajacy",backSlash:"Ukosnik lewy",closeBracket:"Nawias kwadratowy zamykajacy",singleQuote:"Apostrof"});
