/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","sk",{title:"Inštrukcie prístupnosti",contents:"Pomocný obsah. Pre zatvorenie tohto okna, stlacte ESC.",legend:[{name:"Všeobecne",items:[{name:"Lišta nástrojov editora",legend:"Stlacte ${toolbarFocus} pre navigáciu na lištu nástrojov. Medzi dalšou a predchádzajúcou lištou nástrojov sa pohybujete s TAB a SHIFT+TAB. Medzi dalším a predchádzajúcim tlacidlom na lište nástrojov sa pohybujete s pravou šípkou a lavou šípkou. Stlacte medzerník alebo ENTER pre aktiváciu tlacidla lišty nástrojov."},
{name:"Editorový dialóg",legend:"V dialógovom okne stlacte TAB pre presun na další prvok, SHIFT+TAB pre presun na predchádzajúci prvok, ENTER pre odoslanie, ESC pre zrušenie. Ked má dialógové okno viacero kariet, zoznam kariet dosiahnete bud stlacením ALT+F10 alebo s TAB v príslušnom poradí kariet. So zameraným zoznamom kariet sa pohybujte k dalšej alebo predchádzajúcej karte cez PRAVÚ a LAVÚ ŠÍPKU."},{name:"Editorové kontextové menu",legend:"Stlacte ${contextMenu} alebo APPLICATION KEY pre otvorenie kontextového menu. Potom sa presúvajte na dalšie možnosti menu s TAB alebo dolnou šípkou. Presunte sa k predchádzajúcej možnosti s SHIFT+TAB alebo hornou šípkou. Stlacte medzerník alebo ENTER pre výber možnosti menu. Otvorte pod-menu danej možnosti s medzerníkom, alebo ENTER, alebo pravou šípkou. Vrátte sa spät do položky rodicovského menu s ESC alebo lavou šípkou. Zatvorte kontextové menu s ESC."},
{name:"Editorov box zoznamu",legend:"V boxe zoznamu, presunte sa na dalšiu položku v zozname s TAB alebo dolnou šípkou. Presunte sa k predchádzajúcej položke v zozname so SHIFT+TAB alebo hornou šípkou. Stlacte medzerník alebo ENTER pre výber možnosti zoznamu. Stlacte ESC pre zatvorenie boxu zoznamu."},{name:"Editorove pásmo cesty prvku",legend:"Stlacte ${elementsPathFocus} pre navigovanie na pásmo cesty elementu. Presunte sa na tlacidlo dalšieho prvku s TAB alebo pravou šípkou. Presunte sa k predchádzajúcemu tlacidlu s SHIFT+TAB alebo lavou šípkou. Stlacte medzerník alebo ENTER pre výber prvku v editore."}]},
{name:"Príkazy",items:[{name:"Vrátit príkazy",legend:"Stlacte ${undo}"},{name:"Nanovo vrátit príkaz",legend:"Stlacte ${redo}"},{name:"Príkaz na stucnenie",legend:"Stlacte ${bold}"},{name:"Príkaz na kurzívu",legend:"Stlacte ${italic}"},{name:"Príkaz na podciarknutie",legend:"Stlacte ${underline}"},{name:"Príkaz na odkaz",legend:"Stlacte ${link}"},{name:"Príkaz na zbalenie lišty nástrojov",legend:"Stlacte ${toolbarCollapse}"},{name:"Prejst na predchádzajúcu zameratelnú medzeru príkazu",legend:"Stlacte ${accessPreviousSpace} pre prístup na najbližšie nedosiahnutelné zameratelné medzery pred vsuvkuo. Napríklad: dve za sebou idúce horizontálne ciary. Opakujte kombináciu klávesov pre dosiahnutie vzdialených zameratelných medzier."},
{name:"Prejst na další ",legend:"Stlacte ${accessNextSpace} pre prístup na najbližšie nedosiahnutelné zameratelné medzery po vsuvke. Napríklad: dve za sebou idúce horizontálne ciary. Opakujte kombináciu klávesov pre dosiahnutie vzdialených zameratelných medzier."},{name:"Pomoc prístupnosti",legend:"Stlacte ${a11yHelp}"},{name:"Vložit ako cistý text",legend:"Stlacte ${pastetext}",legendEdge:"Stlacte ${pastetext} a potom ${paste}"}]}],tab:"Tab",pause:"Pause",capslock:"Caps Lock",escape:"Escape",pageUp:"Stránka hore",
pageDown:"Stránka dole",leftArrow:"Šípka nalavo",upArrow:"Šípka hore",rightArrow:"Šípka napravo",downArrow:"Šípka dole",insert:"Insert",leftWindowKey:"Lavé Windows tlacidlo",rightWindowKey:"Pravé Windows tlacidlo",selectKey:"Tlacidlo Select",numpad0:"Numpad 0",numpad1:"Numpad 1",numpad2:"Numpad 2",numpad3:"Numpad 3",numpad4:"Numpad 4",numpad5:"Numpad 5",numpad6:"Numpad 6",numpad7:"Numpad 7",numpad8:"Numpad 8",numpad9:"Numpad 9",multiply:"Násobenie",add:"Scítanie",subtract:"Odcítanie",decimalPoint:"Desatinná ciarka",
divide:"Delenie",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"Bodkociarka",equalSign:"Rovná sa",comma:"Ciarka",dash:"Pomlcka",period:"Bodka",forwardSlash:"Lomítko",graveAccent:"Zdôraznovanie prízvuku",openBracket:"Hranatá zátvorka otváracia",backSlash:"Backslash",closeBracket:"Hranatá zátvorka zatváracia",singleQuote:"Jednoduché úvodzovky"});
