/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","tr",{title:"Erisilebilirlik Talimatlari",contents:"Yardim içerigi. Bu pencereyi kapatmak için ESC tusuna basin.",legend:[{name:"Genel",items:[{name:"Düzenleyici Araç Çubugu",legend:"Araç çubugunda gezinmek için ${toolbarFocus} basin. TAB ve SHIFT+TAB ile önceki ve sonraki araç çubugu grubuna tasiyin. SAG OK veya SOL OK ile önceki ve sonraki bir araç çubugu dügmesini hareket ettirin. SPACE tusuna basin veya araç çubugu dügmesini etkinlestirmek için ENTER tusna basin."},
{name:"Diyalog Düzenleyici",legend:"Dialog penceresi içinde, sonraki iletisim alanina gitmek için SEKME tusuna basin, önceki alana geçmek için SHIFT + TAB tusuna basin, pencereyi göndermek için ENTER tusuna basin, dialog penceresini iptal etmek için ESC tusuna basin. Birden çok sekme sayfalari olan diyaloglarin, sekme listesine gitmek için ALT + F10 tuslarina basin. Sonra TAB veya SAG OK sonraki sekmeye tasiyin. SHIFT + TAB veya SOL OK ile önceki sekmeye geçin. Sekme sayfayi seçmek için SPACE veya ENTER tusuna basin."},
{name:"Içerik Menü Editörü",legend:"Içerik menüsünü açmak için ${contextMenu} veya UYGULAMA TUSU'na basin. Daha sonra SEKME veya ASAGI OK ile bir sonraki menü seçenegi tasiyin. SHIFT + TAB veya YUKARI OK ile önceki seçenege gider. Menü seçenegini seçmek için SPACE veya ENTER tusuna basin. Seçili seçenegin alt menüsünü SPACE ya da ENTER veya SAG OK açin. Üst menü ögesini geçmek için ESC veya SOL OK ile geri dönün. ESC ile baglam menüsünü kapatin."},{name:"Liste Kutusu Editörü",legend:"Liste kutusu içinde, bir sonraki liste ögesine SEKME VEYA ASAGI OK ile tasiyin. SHIFT+TAB veya YUKARI önceki liste ögesi tasiyin. Liste seçenegi seçmek için SPACE veya ENTER tusuna basin. Liste kutusunu kapatmak için ESC tusuna basin."},
{name:"Element Yol Çubugu Editörü",legend:"Elementlerin yol çubugunda gezinmek için ${ElementsPathFocus} basin. SEKME veya SAG OK ile sonraki element dügmesine tasiyin. SHIFT+TAB veya SOL OK önceki dügmeye hareket ettirin. Editör içindeki elementi seçmek için ENTER veya SPACE tusuna basin."}]},{name:"Komutlar",items:[{name:"Komutu geri al",legend:"$(undo)'ya basin"},{name:"Komutu geri al",legend:"${redo} basin"},{name:" Kalin komut",legend:"${bold} basin"},{name:" Italik komutu",legend:"${italic} basin"},
{name:" Alttan çizgi komutu",legend:"${underline} basin"},{name:" Baglanti komutu",legend:"${link} basin"},{name:" Araç çubugu Toplama komutu",legend:"${toolbarCollapse} basin"},{name:"Önceki komut alanina odaklan",legend:"Düzeltme imleçinden önce, en yakin uzaktaki alana erismek için ${accessPreviousSpace} basin, örnegin: iki birlesik HR elementleri. Ayni tus kombinasyonu tekrariyla diger alanlarada ulasin."},{name:"Sonraki komut alanina odaklan",legend:"Düzeltme imleçinden sonra, en yakin uzaktaki alana erismek için ${accessNextSpace} basin, örnegin: iki birlesik HR elementleri. Ayni tus kombinasyonu tekrariyla diger alanlarada ulasin."},
{name:"Erisilebilirlik Yardimi",legend:"${a11yHelp}'e basin"},{name:"Düz Metin Olarak Yapistir",legend:"${pastetext} basin",legendEdge:"Önce ${pastetext} ardindan${paste} basin"}]}],tab:"Sekme tusu",pause:"Durdurma tusu",capslock:"Büyük harf tusu",escape:"Vazgeç tusu",pageUp:"Sayfa Yukari",pageDown:"Sayfa Asagi",leftArrow:"Sol ok",upArrow:"Yukari ok",rightArrow:"Sag ok",downArrow:"Asagi ok",insert:"Araya gir",leftWindowKey:"Sol windows tusu",rightWindowKey:"Sag windows tusu",selectKey:"Seçme tusu",
numpad0:"Nümerik 0",numpad1:"Nümerik 1",numpad2:"Nümerik 2",numpad3:"Nümerik 3",numpad4:"Nümerik 4",numpad5:"Nümerik 5",numpad6:"Nümerik 6",numpad7:"Nümerik 7",numpad8:"Nümerik 8",numpad9:"Nümerik 9",multiply:"Çarpma",add:"Toplama",subtract:"Çikarma",decimalPoint:"Ondalik isareti",divide:"Bölme",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lk",scrollLock:"Scr Lk",semiColon:"Noktali virgül",equalSign:"Esittir",comma:"Virgül",dash:"Eksi",
period:"Nokta",forwardSlash:"Ileri egik çizgi",graveAccent:"Üst tirnak",openBracket:"Parantez aç",backSlash:"Ters egik çizgi",closeBracket:"Parantez kapa",singleQuote:"Tek tirnak"});
