/*
 Copyright (c) 2003-2017, CKSource - Frederico Knabben. All rights reserved.
 For licensing, see LICENSE.md or https://ckeditor.com/legal/ckeditor-oss-license
*/
CKEDITOR.plugins.setLang("a11yhelp","vi",{title:"Hu?ng d?n tr? nang",contents:"N?i dung H? tr?. Nh?n ESC d? dóng h?p tho?i.",legend:[{name:"Chung",items:[{name:"Thanh công c? so?n th?o",legend:"Nh?n ${toolbarFocus} d? di?u hu?ng d?n thanh công c?. Nh?n TAB và SHIFT+TAB d? chuy?n d?n nhóm thanh công c? khác. Nh?n MUI TÊN PH?I ho?c MUI TÊN TRÁI d? chuy?n sang nút khác trên thanh công c?. Nh?n PHÍM CÁCH ho?c ENTER d? kích ho?t nút trên thanh công c?."},{name:"H?p tho?i Biên t",legend:"Inside a dialog, press TAB to navigate to the next dialog element, press SHIFT+TAB to move to the previous dialog element, press ENTER to submit the dialog, press ESC to cancel the dialog. When a dialog has multiple tabs, the tab list can be reached either with ALT+F10 or with TAB as part of the dialog tabbing order. With tab list focused, move to the next and previous tab with RIGHT and LEFT ARROW, respectively."},
{name:"Trình don Ng? c?nh cB? so?n th?o",legend:"Nh?n ${contextMenu} ho?c PHÍM ?NG D?NG d? m? th?c don ng? c?nh. Sau dó nh?n TAB ho?c MUI TÊN XU?NG d? di chuy?n d?n tu? ch?n ti?p theo c?a th?c don. Nh?n SHIFT+TAB ho?c MUI TÊN LÊN d? quay l?i tu? ch?n tru?c. Nh?n D?U CÁCH ho?c ENTER d? ch?n tu? ch?n c?a th?c don. Nh?n D?U CÁCH ho?c ENTER ho?c MUI TÊN SANG PH?I d? m? th?c don con c?a tu? ch?n hi?n t?i. Nh?n ESC ho?c MUI TÊN SANG TRÁI d? quay tr? l?i th?c don g?c. Nh?n ESC d? dóng th?c don ng? c?nh."},
{name:"H?p danh sách trình biên t?p",legend:"Trong m?t danh sách ch?n, di chuy?n d?i tu?ng ti?p theo v?i phím TAB ho?c phím mui tên hu?ng xu?ng. Di chuy?n d?n d?i tu?ng tru?c dó b?ng cách nh?n t? h?p phím SHIFT+TAB ho?c mui tên hu?ng lên. Phím kho?ng cách ho?c phím ENTER d? ch?n các tùy ch?n trong danh sách. Nh?n phím ESC d? dóng l?i danh sách ch?n."},{name:"Thanh du?ng d?n các d?i tu?ng",legend:"Nh?n ${elementsPathFocus} d? di?u hu?ng các d?i tu?ng trong thanh du?ng d?n. Di chuy?n d?n d?i tu?ng ti?p theo b?ng phím TAB ho?c phím mui tên bên ph?i. Di chuy?n d?n d?i tu?ng tru?c dó b?ng t? h?p phím SHIFT+TAB ho?c phím mui tên bên trái. Nh?n phím kho?ng cách ho?c ENTER d? ch?n d?i tu?ng trong trình so?n th?o."}]},
{name:"L?nh",items:[{name:"Làm l?i l?n",legend:"?n ${undo}"},{name:"Làm l?i l?nh",legend:"?n ${redo}"},{name:"L?nh in d?m",legend:"?n ${bold}"},{name:"L?nh in nghiêng",legend:"?n ${italic}"},{name:"L?nh g?ch du?i",legend:"?n ${underline}"},{name:"L?nh liên k?t",legend:"Nh?n ${link}"},{name:"L?nh hi?n th? thanh công c?",legend:"Nh?n${toolbarCollapse}"},{name:"Truy c?p d?n l?nh t?p trung vào kho?ng cách tru?c dó",legend:"?n ${accessPreviousSpace} d? truy c?p d?n ph?n t?p trung kho?ng cách sau ph?n còn sót l?i c?a kho?ng cách g?n nh?t v?n không tác d?ng d?n du?c , thí d?: hai y?u t? di?u ch?nh HR. L?p l?i các phím k?t h?ep này d? vuon d?n ph?n kho?ng cách."},
{name:"Truy c?p ph?n d?i tu?ng l?nh kho?ng tr?ng",legend:"?n ${accessNextSpace} d? truy c?p d?n ph?n t?p trung kho?ng cách sau ph?n còn sót l?i c?a kho?ng cách g?n nh?t v?n không tác d?ng d?n du?c , thí d?: hai y?u t? di?u ch?nh HR. L?p l?i các phím k?t h?ep này d? vuon d?n ph?n kho?ng cách."},{name:"Tr? giúp liên quan",legend:"Nh?n ${a11yHelp}"},{name:" Paste as plain text",legend:"Press ${pastetext}",legendEdge:"Press ${pastetext}, followed by ${paste}"}]}],tab:"Phím Tab",pause:"Phím Pause",capslock:"Phím Caps Lock",
escape:"Phím Escape",pageUp:"Phím Page Up",pageDown:"Phím Page Down",leftArrow:"Phím Left Arrow",upArrow:"Phím Up Arrow",rightArrow:"Phím Right Arrow",downArrow:"Phím Down Arrow",insert:"Chèn",leftWindowKey:"Phím Left Windows",rightWindowKey:"Phím Right Windows ",selectKey:"Ch?n phím",numpad0:"Phím 0",numpad1:"Phím 1",numpad2:"Phím 2",numpad3:"Phím 3",numpad4:"Phím 4",numpad5:"Phím 5",numpad6:"Phím 6",numpad7:"Phím 7",numpad8:"Phím 8",numpad9:"Phím 9",multiply:"Nhân",add:"Thêm",subtract:"Tr?",decimalPoint:"Ði?m s? th?p phân",
divide:"Chia",f1:"F1",f2:"F2",f3:"F3",f4:"F4",f5:"F5",f6:"F6",f7:"F7",f8:"F8",f9:"F9",f10:"F10",f11:"F11",f12:"F12",numLock:"Num Lock",scrollLock:"Scroll Lock",semiColon:"D?u ch?m ph?y",equalSign:"Ðang nh?p b?ng",comma:"D?u ph?y",dash:"D?u g?ch ngang",period:"Phím .",forwardSlash:"Phím /",graveAccent:"Phím `",openBracket:"Open Bracket",backSlash:"D?u g?ch chéo ngu?c",closeBracket:"G?n giá d?",singleQuote:"Trích d?n"});
