// <auto-generated> Ported verbatim from SageFrame/Modules/ROUSER/ROLoginWebService.asmx by tools/port_asmx.py. Do not hand-edit; re-run the tool. </auto-generated>
#pragma warning disable
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.IO;
using Newtonsoft.Json;
using SageFrame.Security;
using SageFrame.Security.Entities;
//using SageFrame.Framework;
using System.Web.Services;
using System.Web.Script.Serialization;
using SageFrame.Security.Helpers;
using SageFrame.Security.Controllers;
using SageFrame.RestroOrder;
using System.Web.Script.Services;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Text;
using Newtonsoft.Json.Linq;

/// <summary>
/// Summary description for PoWebService
/// </summary>
[WebService]
[WebServiceBinding(ConformsTo = WsiProfiles.BasicProfile1_1)]
// To allow this Web Service to be called from script, using ASP.NET AJAX, uncomment the following line. 
[System.Web.Script.Services.ScriptService]
public class RoLoginWebService : System.Web.Services.WebService
{
    // PROD-BUGFIX: legacy had "public static int userid" mutated per login (racy, meaningless across
    // restarts, and never read by the notification SP). Removed — no shared mutable state.
    //public string modulePath = string.Empty;
    //public int userModuleID = 0;
    public RoLoginWebService()
    {
        //modulePath = ResolveUrl(this.AppRelativeTemplateSourceDirectory);
        //userModuleID = int.Parse(SageUserModuleID);
        ////Uncomment the following line if using designed components 
        //InitializeComponent(); 
    }

    [WebMethod]
    [ScriptMethod(UseHttpGet = true, ResponseFormat = ResponseFormat.Json)]
    public void Login(string Username, string Password)
    {

        //json = json.Replace("-",":");
        UserClass usp = new UserClass();
        usp.Username = Username;
        usp.Password = Password;
        usp.OrderMenuListType = System.Configuration.ConfigurationManager.AppSettings["OrderMenuListType"];
        usp.OrderMenuImageshow = System.Configuration.ConfigurationManager.AppSettings["OrderMenuImageshow"];
        string test = JsonConvert.SerializeObject(usp);
        UserClass user = LoginUser(test);


        string jsonString = "";
        JavaScriptSerializer jss = new JavaScriptSerializer();
        //UserClass user = LoginUser(json);
        string success = user.Status;

        jsonString = jss.Serialize(user);

        var parsedJson = JsonConvert.DeserializeObject(jsonString);
        Object jsonFormatted = JsonConvert.SerializeObject(parsedJson, Formatting.Indented);

        //string path = "/Modules/ROUSER/RestrUser.Json";
        //string fullPath = Server.MapPath(path);
        //using (var file = new StreamWriter(fullPath, false))
        //{
        //    file.Flush();
        //    file.Write(jsonFormatted);
        //    file.Close();
        //    file.Dispose();
        //}
        Context.Response.Clear();
        Context.Response.ContentType = "application/json";
        Context.Response.Write(jsonFormatted);
        //if (json != null)
        //{
        //    rsp = new UserClass()
        //    {
        //        Status = "success"
        //    };
        //}
        //else
        //{
        //    rsp = new UserClass()
        //    {
        //        Status = "unsuccess"
        //    };
        //}
        //return JsonConvert.SerializeObject(rsp); 

    }
    [WebMethod]
    [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
    public void TestLogin()
    {
    }

    [WebMethod]
    [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
    public void CheckLogin(string json)
    {
        try
        {
            //string statususer = loginuser(json);
            string jsonString = "";
            JavaScriptSerializer jss = new JavaScriptSerializer();
            UserClass user = LoginUser(json);
            string success = user.Status;

            jsonString = jss.Serialize(user);

            var parsedJson = JsonConvert.DeserializeObject(jsonString);
            dynamic jsonFormatted = JsonConvert.SerializeObject(parsedJson, Formatting.Indented);
            //Object obj = JsonConvert.DeserializeObject(jsonString);
            //Object obj = jsonFormatted;
            //dynamic cycleJson = JObject.Parse(@jsonFormatted);
            //obj = cycleJson;


            //string path = "/Modules/ROUSER/RestrUser.Json";
            //string fullPath = Server.MapPath(path);
            //using (var file = new StreamWriter(fullPath, false))
            //{
            //    file.Flush();
            //    file.Write(jsonFormatted);
            //    file.Close();
            //    file.Dispose();
            //}

            Context.Response.Clear();
            Context.Response.ContentType = "application/json";
            Context.Response.Write(jsonFormatted);

        }
        catch (Exception ex)
        {
            throw ex;
        }
    }
    #region login

    public void SaveWaiterDetailForNotification(UserClass user)
    {
        RestrOrderController.SaveWaiterDetailForNotification(user);
    }




    private UserClass LoginUser(string json)
    {

        string jsonString = null;
        //string json = "";
        JavaScriptSerializer jss = new JavaScriptSerializer();
        UserClass userClass = new UserClass();
        userClass = jss.Deserialize<UserClass>(json);
        MembershipController member = new MembershipController();
        RoleController role = new RoleController();
        UserInfo user = member.GetUserDetails(1, userClass.Username);
        if (user.UserExists)
        {
            List<UserInfo> UserDetail = RestrOrderController.GetUsersDetail(user.UserID, user.UserName);
            string Roles = string.Empty;
            foreach (UserInfo item in UserDetail)
            {
                if (Roles == "")
                {
                    Roles = item.RoleNames;
                }
                else
                {
                    Roles = Roles + "," + item.RoleNames;
                }

            }
            user.RoleNames = Roles;
            //HttpContext.Current.Session[SessionKeys.IsLoginClick] = false;
            userClass.RoleNames = Roles;
        }


        //userClass.Username = userName;
        //userClass.Password = password;
        if (user.UserExists && user.IsApproved)
        {
            if (PasswordHelper.ValidateUser(user.PasswordFormat, userClass.Password, user.Password, user.PasswordSalt))
            {
                // BUGFIX (prod review): legacy used a static counter here ("userid += 1") — racy across threads
                // and meaningless across restarts. UserID is not consumed by the notification SP
                // (usp_SaveWaiterDetailForNotification uses @WaiterName/@WaiterIP only), so bind a stable
                // deterministic value derived from the real account GUID. No shared mutable state.
                userClass.UserID = user.UserID.ToString("N").GetHashCode();
                //login is successfull SucessFullLogin(user);
                if (userClass.RoleNames != "KitchenOrder")
                {
                    SaveWaiterDetailForNotification(userClass);
                }
                userClass.Status = "Success";


            }
            else
            {
                userClass.Status = "Failed";
            }
        }
        else
        {
            userClass.Status = "Failed";
        }
        userClass.Password = "Encrypted";
        userClass.OrderMenuListType = System.Configuration.ConfigurationManager.AppSettings["OrderMenuListType"];
        userClass.OrderMenuImageshow = System.Configuration.ConfigurationManager.AppSettings["OrderMenuImageshow"];
        //var test = JObject.Parse(JsonConvert.SerializeObject(userClass)); ;
        //return test;
        // return userClass;
        jsonString = jss.Serialize(userClass);
        return userClass;

    }
    #endregion


    [WebMethod]
    [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
    public void LoggedOut(string json)
    {
        //string json = "";
        UserClass userClass = new UserClass();
        JavaScriptSerializer jss = new JavaScriptSerializer();
        userClass = jss.Deserialize<UserClass>(json);

        MembershipController member = new MembershipController();
        RoleController role = new RoleController();
        role.LoggoutUser(userClass.Username);

        // WaiterCallInfo info = RestrOrderController.DeleteWaiterFromLog(userClass.Username);
        //RestrOrderController.DeleteWaiterFromLog(userClass.Username);

    }
    [WebMethod]
    public void getWaiterList()
    {
        try
        {
            RestrOrderController con = new RestrOrderController();
            List<WaiterCallInfo> wait = con.GetWaiterLog();
            string jsonString = "";
            jsonString = Newtonsoft.Json.JsonConvert.SerializeObject(wait, Newtonsoft.Json.Formatting.Indented);
            //string path = "/Modules/ROUSER/WaiterCall.Json";
            //string fullPath = Server.MapPath(path);
            //using (var file = new System.IO.StreamWriter(fullPath, false))
            //{
            //    file.Flush();
            //    file.Write(jsonString);
            //    file.Close();
            //    file.Dispose();
            //}
            Context.Response.Clear();
            Context.Response.ContentType = "application/json";
            Context.Response.Write(jsonString);
        }
        catch (Exception)
        {
            throw;
        }
    }
    public class PinLogin
    {
        public string pin { get; set; }
        public string WaiterIP { get; set; }

    }
    [WebMethod]
    [ScriptMethod(ResponseFormat = ResponseFormat.Json)]
    public void LoginPin(string json)
    {
        RestrOrderController roc = new RestrOrderController();
        JavaScriptSerializer jss = new JavaScriptSerializer();
        PinLogin loginClass = new PinLogin();
        loginClass = jss.Deserialize<PinLogin>(json);
        UserClass userClass = new UserClass();
        PinUser info = roc.CheckPin(loginClass.pin);
        string jsonString = "";
        //string success = user.Status;
        //jsonString = jss.Serialize(user);

        if (info != null)
        {

            info.Message = "Success";
            info.OrderMenuListType = System.Configuration.ConfigurationManager.AppSettings["OrderMenuListType"];
            info.OrderMenuImageshow = System.Configuration.ConfigurationManager.AppSettings["OrderMenuImageshow"];
            jsonString = jss.Serialize(info);
            userClass.Username = info.UserName;
            userClass.WaiterIP = loginClass.WaiterIP;

            if (info.Roles != "KitchenOrder")
            {
                SaveWaiterDetailForNotification(userClass);
            }

            var parsedJson = JsonConvert.DeserializeObject(jsonString);
            jsonString = "{statusCode:200, message: \"Success\", data:"+ JsonConvert.SerializeObject(parsedJson, Formatting.Indented)+"}";

        }
        else
        {
            jsonString = "{statusCode:100, message:\"Invalid PIN Code.\"}";
        }
        //jsonString = JsonConvert.SerializeObject(rooms, Formatting.Indented);
        //string path = "/Modules/ROUSER/PinLoginUser.Json";
        //string fullPath = Server.MapPath(path);
        //using (var file = new StreamWriter(fullPath, false))
        //{
        //    file.Flush();
        //    file.Write(jsonString);
        //    file.Close();
        //    file.Dispose();
        //}

        Context.Response.Clear();
        Context.Response.ContentType = "application/json";
        Context.Response.Write(jsonString);
    }
}

    
