SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO

--select * FROM H_LostAndFound
CREATE PROCEDURE [dbo].[usp_H_DeleteLostAndFound]
	@LF_ID INT	
AS
	BEGIN
	DELETE FROM H_LostAndFound WHERE LF_ID = @LF_ID
END

GO
