SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_GETRESTROROOMIDFROMTYPE]
 @RoomTypeID INT
AS
BEGIN
	 Select * from RO_RestroRoom where RoomTypeID = @RoomTypeID
	 order by restroRoom
END


GO
