SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE PROCEDURE [dbo].[USP_GETPURCHASEORDERBYORDER] (  
 @OrderId INT  
 )  
AS  
 BEGIN  
  SELECT * FROM tblPurchaseOrder WHERE OrderId=@OrderId;
END

GO
