using System;
// <auto-generated> typed wrappers for legacy generic SQLHandler calls.
#pragma warning disable
using System.Collections.Generic;
using System.Data;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.FiscalYear;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestoLoyalty;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.Security.Entities;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestoLoyalty;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
using SageFrame.RestroOrder;
namespace SageFrame.Web.Utilities {
public partial class SQLHandler { public List<ActivityLog> ExecuteAsList_ActivityLog(string sp, object ps = null) => ExecuteAsList<ActivityLog>(sp, ToColl(ps)); public ActivityLog ExecuteAsObject_ActivityLog(string sp, object ps = null) => ExecuteAsObject<ActivityLog>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<AdjustmentDetails> ExecuteAsList_AdjustmentDetails(string sp, object ps = null) => ExecuteAsList<AdjustmentDetails>(sp, ToColl(ps)); public AdjustmentDetails ExecuteAsObject_AdjustmentDetails(string sp, object ps = null) => ExecuteAsObject<AdjustmentDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<AdjustmentType> ExecuteAsList_AdjustmentType(string sp, object ps = null) => ExecuteAsList<AdjustmentType>(sp, ToColl(ps)); public AdjustmentType ExecuteAsObject_AdjustmentType(string sp, object ps = null) => ExecuteAsObject<AdjustmentType>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<BillInfo> ExecuteAsList_BillInfo(string sp, object ps = null) => ExecuteAsList<BillInfo>(sp, ToColl(ps)); public BillInfo ExecuteAsObject_BillInfo(string sp, object ps = null) => ExecuteAsObject<BillInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<BillPostLog> ExecuteAsList_BillPostLog(string sp, object ps = null) => ExecuteAsList<BillPostLog>(sp, ToColl(ps)); public BillPostLog ExecuteAsObject_BillPostLog(string sp, object ps = null) => ExecuteAsObject<BillPostLog>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CardProvider> ExecuteAsList_CardProvider(string sp, object ps = null) => ExecuteAsList<CardProvider>(sp, ToColl(ps)); public CardProvider ExecuteAsObject_CardProvider(string sp, object ps = null) => ExecuteAsObject<CardProvider>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CashDenomination> ExecuteAsList_CashDenomination(string sp, object ps = null) => ExecuteAsList<CashDenomination>(sp, ToColl(ps)); public CashDenomination ExecuteAsObject_CashDenomination(string sp, object ps = null) => ExecuteAsObject<CashDenomination>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CategoriesClass> ExecuteAsList_CategoriesClass(string sp, object ps = null) => ExecuteAsList<CategoriesClass>(sp, ToColl(ps)); public CategoriesClass ExecuteAsObject_CategoriesClass(string sp, object ps = null) => ExecuteAsObject<CategoriesClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CbmsData> ExecuteAsList_CbmsData(string sp, object ps = null) => ExecuteAsList<CbmsData>(sp, ToColl(ps)); public CbmsData ExecuteAsObject_CbmsData(string sp, object ps = null) => ExecuteAsObject<CbmsData>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CbmsSyncedData> ExecuteAsList_CbmsSyncedData(string sp, object ps = null) => ExecuteAsList<CbmsSyncedData>(sp, ToColl(ps)); public CbmsSyncedData ExecuteAsObject_CbmsSyncedData(string sp, object ps = null) => ExecuteAsObject<CbmsSyncedData>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CheckBill> ExecuteAsList_CheckBill(string sp, object ps = null) => ExecuteAsList<CheckBill>(sp, ToColl(ps)); public CheckBill ExecuteAsObject_CheckBill(string sp, object ps = null) => ExecuteAsObject<CheckBill>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ClassforMenuItem> ExecuteAsList_ClassforMenuItem(string sp, object ps = null) => ExecuteAsList<ClassforMenuItem>(sp, ToColl(ps)); public ClassforMenuItem ExecuteAsObject_ClassforMenuItem(string sp, object ps = null) => ExecuteAsObject<ClassforMenuItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ClosingReport> ExecuteAsList_ClosingReport(string sp, object ps = null) => ExecuteAsList<ClosingReport>(sp, ToColl(ps)); public ClosingReport ExecuteAsObject_ClosingReport(string sp, object ps = null) => ExecuteAsObject<ClosingReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CogsReport> ExecuteAsList_CogsReport(string sp, object ps = null) => ExecuteAsList<CogsReport>(sp, ToColl(ps)); public CogsReport ExecuteAsObject_CogsReport(string sp, object ps = null) => ExecuteAsObject<CogsReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ComplimentaryOrder> ExecuteAsList_ComplimentaryOrder(string sp, object ps = null) => ExecuteAsList<ComplimentaryOrder>(sp, ToColl(ps)); public ComplimentaryOrder ExecuteAsObject_ComplimentaryOrder(string sp, object ps = null) => ExecuteAsObject<ComplimentaryOrder>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ConsumptionReport> ExecuteAsList_ConsumptionReport(string sp, object ps = null) => ExecuteAsList<ConsumptionReport>(sp, ToColl(ps)); public ConsumptionReport ExecuteAsObject_ConsumptionReport(string sp, object ps = null) => ExecuteAsObject<ConsumptionReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CostCenterGroup> ExecuteAsList_CostCenterGroup(string sp, object ps = null) => ExecuteAsList<CostCenterGroup>(sp, ToColl(ps)); public CostCenterGroup ExecuteAsObject_CostCenterGroup(string sp, object ps = null) => ExecuteAsObject<CostCenterGroup>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CreditPayReport> ExecuteAsList_CreditPayReport(string sp, object ps = null) => ExecuteAsList<CreditPayReport>(sp, ToColl(ps)); public CreditPayReport ExecuteAsObject_CreditPayReport(string sp, object ps = null) => ExecuteAsObject<CreditPayReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CreditorBalanceReport> ExecuteAsList_CreditorBalanceReport(string sp, object ps = null) => ExecuteAsList<CreditorBalanceReport>(sp, ToColl(ps)); public CreditorBalanceReport ExecuteAsObject_CreditorBalanceReport(string sp, object ps = null) => ExecuteAsObject<CreditorBalanceReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CurrencyClass> ExecuteAsList_CurrencyClass(string sp, object ps = null) => ExecuteAsList<CurrencyClass>(sp, ToColl(ps)); public CurrencyClass ExecuteAsObject_CurrencyClass(string sp, object ps = null) => ExecuteAsObject<CurrencyClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<CustomerEvent> ExecuteAsList_CustomerEvent(string sp, object ps = null) => ExecuteAsList<CustomerEvent>(sp, ToColl(ps)); public CustomerEvent ExecuteAsObject_CustomerEvent(string sp, object ps = null) => ExecuteAsObject<CustomerEvent>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<DailyClosingReport> ExecuteAsList_DailyClosingReport(string sp, object ps = null) => ExecuteAsList<DailyClosingReport>(sp, ToColl(ps)); public DailyClosingReport ExecuteAsObject_DailyClosingReport(string sp, object ps = null) => ExecuteAsObject<DailyClosingReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<EnumClass> ExecuteAsList_EnumClass(string sp, object ps = null) => ExecuteAsList<EnumClass>(sp, ToColl(ps)); public EnumClass ExecuteAsObject_EnumClass(string sp, object ps = null) => ExecuteAsObject<EnumClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SageFrame.RestroOrder.FiscalYear> ExecuteAsList_FiscalYear(string sp, object ps = null) => ExecuteAsList<SageFrame.RestroOrder.FiscalYear>(sp, ToColl(ps)); public SageFrame.RestroOrder.FiscalYear ExecuteAsObject_FiscalYear(string sp, object ps = null) => ExecuteAsObject<SageFrame.RestroOrder.FiscalYear>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<FiscalYearInfo> ExecuteAsList_FiscalYearInfo(string sp, object ps = null) => ExecuteAsList<FiscalYearInfo>(sp, ToColl(ps)); public FiscalYearInfo ExecuteAsObject_FiscalYearInfo(string sp, object ps = null) => ExecuteAsObject<FiscalYearInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<GroupWithItem> ExecuteAsList_GroupWithItem(string sp, object ps = null) => ExecuteAsList<GroupWithItem>(sp, ToColl(ps)); public GroupWithItem ExecuteAsObject_GroupWithItem(string sp, object ps = null) => ExecuteAsObject<GroupWithItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<IngredientItems> ExecuteAsList_IngredientItems(string sp, object ps = null) => ExecuteAsList<IngredientItems>(sp, ToColl(ps)); public IngredientItems ExecuteAsObject_IngredientItems(string sp, object ps = null) => ExecuteAsObject<IngredientItems>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ItemGroup> ExecuteAsList_ItemGroup(string sp, object ps = null) => ExecuteAsList<ItemGroup>(sp, ToColl(ps)); public ItemGroup ExecuteAsObject_ItemGroup(string sp, object ps = null) => ExecuteAsObject<ItemGroup>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ItemLedger> ExecuteAsList_ItemLedger(string sp, object ps = null) => ExecuteAsList<ItemLedger>(sp, ToColl(ps)); public ItemLedger ExecuteAsObject_ItemLedger(string sp, object ps = null) => ExecuteAsObject<ItemLedger>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ItemShiftReport> ExecuteAsList_ItemShiftReport(string sp, object ps = null) => ExecuteAsList<ItemShiftReport>(sp, ToColl(ps)); public ItemShiftReport ExecuteAsObject_ItemShiftReport(string sp, object ps = null) => ExecuteAsObject<ItemShiftReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ItemsClass> ExecuteAsList_ItemsClass(string sp, object ps = null) => ExecuteAsList<ItemsClass>(sp, ToColl(ps)); public ItemsClass ExecuteAsObject_ItemsClass(string sp, object ps = null) => ExecuteAsObject<ItemsClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<LanguageMenu> ExecuteAsList_LanguageMenu(string sp, object ps = null) => ExecuteAsList<LanguageMenu>(sp, ToColl(ps)); public LanguageMenu ExecuteAsObject_LanguageMenu(string sp, object ps = null) => ExecuteAsObject<LanguageMenu>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<License> ExecuteAsList_License(string sp, object ps = null) => ExecuteAsList<License>(sp, ToColl(ps)); public License ExecuteAsObject_License(string sp, object ps = null) => ExecuteAsObject<License>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MaterializedReport> ExecuteAsList_MaterializedReport(string sp, object ps = null) => ExecuteAsList<MaterializedReport>(sp, ToColl(ps)); public MaterializedReport ExecuteAsObject_MaterializedReport(string sp, object ps = null) => ExecuteAsObject<MaterializedReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MemberInfo> ExecuteAsList_MemberInfo(string sp, object ps = null) => ExecuteAsList<MemberInfo>(sp, ToColl(ps)); public MemberInfo ExecuteAsObject_MemberInfo(string sp, object ps = null) => ExecuteAsObject<MemberInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MenuClass> ExecuteAsList_MenuClass(string sp, object ps = null) => ExecuteAsList<MenuClass>(sp, ToColl(ps)); public MenuClass ExecuteAsObject_MenuClass(string sp, object ps = null) => ExecuteAsObject<MenuClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MergeTableInfo> ExecuteAsList_MergeTableInfo(string sp, object ps = null) => ExecuteAsList<MergeTableInfo>(sp, ToColl(ps)); public MergeTableInfo ExecuteAsObject_MergeTableInfo(string sp, object ps = null) => ExecuteAsObject<MergeTableInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MvPurchaseDetails> ExecuteAsList_MvPurchaseDetails(string sp, object ps = null) => ExecuteAsList<MvPurchaseDetails>(sp, ToColl(ps)); public MvPurchaseDetails ExecuteAsObject_MvPurchaseDetails(string sp, object ps = null) => ExecuteAsObject<MvPurchaseDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<MvPurchaseMain> ExecuteAsList_MvPurchaseMain(string sp, object ps = null) => ExecuteAsList<MvPurchaseMain>(sp, ToColl(ps)); public MvPurchaseMain ExecuteAsObject_MvPurchaseMain(string sp, object ps = null) => ExecuteAsObject<MvPurchaseMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<OrderDetailCancel> ExecuteAsList_OrderDetailCancel(string sp, object ps = null) => ExecuteAsList<OrderDetailCancel>(sp, ToColl(ps)); public OrderDetailCancel ExecuteAsObject_OrderDetailCancel(string sp, object ps = null) => ExecuteAsObject<OrderDetailCancel>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<OrderDetailClass> ExecuteAsList_OrderDetailClass(string sp, object ps = null) => ExecuteAsList<OrderDetailClass>(sp, ToColl(ps)); public OrderDetailClass ExecuteAsObject_OrderDetailClass(string sp, object ps = null) => ExecuteAsObject<OrderDetailClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<OrderExtraItem> ExecuteAsList_OrderExtraItem(string sp, object ps = null) => ExecuteAsList<OrderExtraItem>(sp, ToColl(ps)); public OrderExtraItem ExecuteAsObject_OrderExtraItem(string sp, object ps = null) => ExecuteAsObject<OrderExtraItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<OrderMasterClass> ExecuteAsList_OrderMasterClass(string sp, object ps = null) => ExecuteAsList<OrderMasterClass>(sp, ToColl(ps)); public OrderMasterClass ExecuteAsObject_OrderMasterClass(string sp, object ps = null) => ExecuteAsObject<OrderMasterClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<PaymentModes> ExecuteAsList_PaymentModes(string sp, object ps = null) => ExecuteAsList<PaymentModes>(sp, ToColl(ps)); public PaymentModes ExecuteAsObject_PaymentModes(string sp, object ps = null) => ExecuteAsObject<PaymentModes>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<PinUser> ExecuteAsList_PinUser(string sp, object ps = null) => ExecuteAsList<PinUser>(sp, ToColl(ps)); public PinUser ExecuteAsObject_PinUser(string sp, object ps = null) => ExecuteAsObject<PinUser>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<PrintDetail> ExecuteAsList_PrintDetail(string sp, object ps = null) => ExecuteAsList<PrintDetail>(sp, ToColl(ps)); public PrintDetail ExecuteAsObject_PrintDetail(string sp, object ps = null) => ExecuteAsObject<PrintDetail>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ProductionDetails> ExecuteAsList_ProductionDetails(string sp, object ps = null) => ExecuteAsList<ProductionDetails>(sp, ToColl(ps)); public ProductionDetails ExecuteAsObject_ProductionDetails(string sp, object ps = null) => ExecuteAsObject<ProductionDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ProductionMain> ExecuteAsList_ProductionMain(string sp, object ps = null) => ExecuteAsList<ProductionMain>(sp, ToColl(ps)); public ProductionMain ExecuteAsObject_ProductionMain(string sp, object ps = null) => ExecuteAsObject<ProductionMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<PurchaseReturnDetails> ExecuteAsList_PurchaseReturnDetails(string sp, object ps = null) => ExecuteAsList<PurchaseReturnDetails>(sp, ToColl(ps)); public PurchaseReturnDetails ExecuteAsObject_PurchaseReturnDetails(string sp, object ps = null) => ExecuteAsObject<PurchaseReturnDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<PurchaseReturnMain> ExecuteAsList_PurchaseReturnMain(string sp, object ps = null) => ExecuteAsList<PurchaseReturnMain>(sp, ToColl(ps)); public PurchaseReturnMain ExecuteAsObject_PurchaseReturnMain(string sp, object ps = null) => ExecuteAsObject<PurchaseReturnMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ROInvItem> ExecuteAsList_ROInvItem(string sp, object ps = null) => ExecuteAsList<ROInvItem>(sp, ToColl(ps)); public ROInvItem ExecuteAsObject_ROInvItem(string sp, object ps = null) => ExecuteAsObject<ROInvItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ROInvItemForApi> ExecuteAsList_ROInvItemForApi(string sp, object ps = null) => ExecuteAsList<ROInvItemForApi>(sp, ToColl(ps)); public ROInvItemForApi ExecuteAsObject_ROInvItemForApi(string sp, object ps = null) => ExecuteAsObject<ROInvItemForApi>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<Recquistion> ExecuteAsList_Recquistion(string sp, object ps = null) => ExecuteAsList<Recquistion>(sp, ToColl(ps)); public Recquistion ExecuteAsObject_Recquistion(string sp, object ps = null) => ExecuteAsObject<Recquistion>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<RecquistionDetails> ExecuteAsList_RecquistionDetails(string sp, object ps = null) => ExecuteAsList<RecquistionDetails>(sp, ToColl(ps)); public RecquistionDetails ExecuteAsObject_RecquistionDetails(string sp, object ps = null) => ExecuteAsObject<RecquistionDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<RestrOrderInfo> ExecuteAsList_RestrOrderInfo(string sp, object ps = null) => ExecuteAsList<RestrOrderInfo>(sp, ToColl(ps)); public RestrOrderInfo ExecuteAsObject_RestrOrderInfo(string sp, object ps = null) => ExecuteAsObject<RestrOrderInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<RestroRoom> ExecuteAsList_RestroRoom(string sp, object ps = null) => ExecuteAsList<RestroRoom>(sp, ToColl(ps)); public RestroRoom ExecuteAsObject_RestroRoom(string sp, object ps = null) => ExecuteAsObject<RestroRoom>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ReturnBillPostLog> ExecuteAsList_ReturnBillPostLog(string sp, object ps = null) => ExecuteAsList<ReturnBillPostLog>(sp, ToColl(ps)); public ReturnBillPostLog ExecuteAsObject_ReturnBillPostLog(string sp, object ps = null) => ExecuteAsObject<ReturnBillPostLog>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<RoomBookingsInfo> ExecuteAsList_RoomBookingsInfo(string sp, object ps = null) => ExecuteAsList<RoomBookingsInfo>(sp, ToColl(ps)); public RoomBookingsInfo ExecuteAsObject_RoomBookingsInfo(string sp, object ps = null) => ExecuteAsObject<RoomBookingsInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<RoomType> ExecuteAsList_RoomType(string sp, object ps = null) => ExecuteAsList<RoomType>(sp, ToColl(ps)); public RoomType ExecuteAsObject_RoomType(string sp, object ps = null) => ExecuteAsObject<RoomType>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesChart> ExecuteAsList_SalesChart(string sp, object ps = null) => ExecuteAsList<SalesChart>(sp, ToColl(ps)); public SalesChart ExecuteAsObject_SalesChart(string sp, object ps = null) => ExecuteAsObject<SalesChart>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesDetailClass> ExecuteAsList_SalesDetailClass(string sp, object ps = null) => ExecuteAsList<SalesDetailClass>(sp, ToColl(ps)); public SalesDetailClass ExecuteAsObject_SalesDetailClass(string sp, object ps = null) => ExecuteAsObject<SalesDetailClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesMaster> ExecuteAsList_SalesMaster(string sp, object ps = null) => ExecuteAsList<SalesMaster>(sp, ToColl(ps)); public SalesMaster ExecuteAsObject_SalesMaster(string sp, object ps = null) => ExecuteAsObject<SalesMaster>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesPayment> ExecuteAsList_SalesPayment(string sp, object ps = null) => ExecuteAsList<SalesPayment>(sp, ToColl(ps)); public SalesPayment ExecuteAsObject_SalesPayment(string sp, object ps = null) => ExecuteAsObject<SalesPayment>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesReport> ExecuteAsList_SalesReport(string sp, object ps = null) => ExecuteAsList<SalesReport>(sp, ToColl(ps)); public SalesReport ExecuteAsObject_SalesReport(string sp, object ps = null) => ExecuteAsObject<SalesReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SalesSummaryReport> ExecuteAsList_SalesSummaryReport(string sp, object ps = null) => ExecuteAsList<SalesSummaryReport>(sp, ToColl(ps)); public SalesSummaryReport ExecuteAsObject_SalesSummaryReport(string sp, object ps = null) => ExecuteAsObject<SalesSummaryReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<StatementInfo> ExecuteAsList_StatementInfo(string sp, object ps = null) => ExecuteAsList<StatementInfo>(sp, ToColl(ps)); public StatementInfo ExecuteAsObject_StatementInfo(string sp, object ps = null) => ExecuteAsObject<StatementInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<StockDetail> ExecuteAsList_StockDetail(string sp, object ps = null) => ExecuteAsList<StockDetail>(sp, ToColl(ps)); public StockDetail ExecuteAsObject_StockDetail(string sp, object ps = null) => ExecuteAsObject<StockDetail>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<StockReport> ExecuteAsList_StockReport(string sp, object ps = null) => ExecuteAsList<StockReport>(sp, ToColl(ps)); public StockReport ExecuteAsObject_StockReport(string sp, object ps = null) => ExecuteAsObject<StockReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<StoreItemStock> ExecuteAsList_StoreItemStock(string sp, object ps = null) => ExecuteAsList<StoreItemStock>(sp, ToColl(ps)); public StoreItemStock ExecuteAsObject_StoreItemStock(string sp, object ps = null) => ExecuteAsObject<StoreItemStock>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<SummaryReport> ExecuteAsList_SummaryReport(string sp, object ps = null) => ExecuteAsList<SummaryReport>(sp, ToColl(ps)); public SummaryReport ExecuteAsObject_SummaryReport(string sp, object ps = null) => ExecuteAsObject<SummaryReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<TableReservation> ExecuteAsList_TableReservation(string sp, object ps = null) => ExecuteAsList<TableReservation>(sp, ToColl(ps)); public TableReservation ExecuteAsObject_TableReservation(string sp, object ps = null) => ExecuteAsObject<TableReservation>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<TargetSales> ExecuteAsList_TargetSales(string sp, object ps = null) => ExecuteAsList<TargetSales>(sp, ToColl(ps)); public TargetSales ExecuteAsObject_TargetSales(string sp, object ps = null) => ExecuteAsObject<TargetSales>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<TargetSalesItem> ExecuteAsList_TargetSalesItem(string sp, object ps = null) => ExecuteAsList<TargetSalesItem>(sp, ToColl(ps)); public TargetSalesItem ExecuteAsObject_TargetSalesItem(string sp, object ps = null) => ExecuteAsObject<TargetSalesItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<Token> ExecuteAsList_Token(string sp, object ps = null) => ExecuteAsList<Token>(sp, ToColl(ps)); public Token ExecuteAsObject_Token(string sp, object ps = null) => ExecuteAsObject<Token>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<Unit> ExecuteAsList_Unit(string sp, object ps = null) => ExecuteAsList<Unit>(sp, ToColl(ps)); public Unit ExecuteAsObject_Unit(string sp, object ps = null) => ExecuteAsObject<Unit>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<UnitClass> ExecuteAsList_UnitClass(string sp, object ps = null) => ExecuteAsList<UnitClass>(sp, ToColl(ps)); public UnitClass ExecuteAsObject_UnitClass(string sp, object ps = null) => ExecuteAsObject<UnitClass>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<UnitConversion> ExecuteAsList_UnitConversion(string sp, object ps = null) => ExecuteAsList<UnitConversion>(sp, ToColl(ps)); public UnitConversion ExecuteAsObject_UnitConversion(string sp, object ps = null) => ExecuteAsObject<UnitConversion>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<UnpaidBills> ExecuteAsList_UnpaidBills(string sp, object ps = null) => ExecuteAsList<UnpaidBills>(sp, ToColl(ps)); public UnpaidBills ExecuteAsObject_UnpaidBills(string sp, object ps = null) => ExecuteAsObject<UnpaidBills>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<UserInfo> ExecuteAsList_UserInfo(string sp, object ps = null) => ExecuteAsList<UserInfo>(sp, ToColl(ps)); public UserInfo ExecuteAsObject_UserInfo(string sp, object ps = null) => ExecuteAsObject<UserInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<UserInfos> ExecuteAsList_UserInfos(string sp, object ps = null) => ExecuteAsList<UserInfos>(sp, ToColl(ps)); public UserInfos ExecuteAsObject_UserInfos(string sp, object ps = null) => ExecuteAsObject<UserInfos>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<WaiterCallInfo> ExecuteAsList_WaiterCallInfo(string sp, object ps = null) => ExecuteAsList<WaiterCallInfo>(sp, ToColl(ps)); public WaiterCallInfo ExecuteAsObject_WaiterCallInfo(string sp, object ps = null) => ExecuteAsObject<WaiterCallInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<adjustmentMain> ExecuteAsList_adjustmentMain(string sp, object ps = null) => ExecuteAsList<adjustmentMain>(sp, ToColl(ps)); public adjustmentMain ExecuteAsObject_adjustmentMain(string sp, object ps = null) => ExecuteAsObject<adjustmentMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<bestby> ExecuteAsList_bestby(string sp, object ps = null) => ExecuteAsList<bestby>(sp, ToColl(ps)); public bestby ExecuteAsObject_bestby(string sp, object ps = null) => ExecuteAsObject<bestby>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<billTermDetails> ExecuteAsList_billTermDetails(string sp, object ps = null) => ExecuteAsList<billTermDetails>(sp, ToColl(ps)); public billTermDetails ExecuteAsObject_billTermDetails(string sp, object ps = null) => ExecuteAsObject<billTermDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<billingTerm> ExecuteAsList_billingTerm(string sp, object ps = null) => ExecuteAsList<billingTerm>(sp, ToColl(ps)); public billingTerm ExecuteAsObject_billingTerm(string sp, object ps = null) => ExecuteAsObject<billingTerm>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<companyInfo> ExecuteAsList_companyInfo(string sp, object ps = null) => ExecuteAsList<companyInfo>(sp, ToColl(ps)); public companyInfo ExecuteAsObject_companyInfo(string sp, object ps = null) => ExecuteAsObject<companyInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<costCenter> ExecuteAsList_costCenter(string sp, object ps = null) => ExecuteAsList<costCenter>(sp, ToColl(ps)); public costCenter ExecuteAsObject_costCenter(string sp, object ps = null) => ExecuteAsObject<costCenter>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<costCenterReport> ExecuteAsList_costCenterReport(string sp, object ps = null) => ExecuteAsList<costCenterReport>(sp, ToColl(ps)); public costCenterReport ExecuteAsObject_costCenterReport(string sp, object ps = null) => ExecuteAsObject<costCenterReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<cumbomain> ExecuteAsList_cumbomain(string sp, object ps = null) => ExecuteAsList<cumbomain>(sp, ToColl(ps)); public cumbomain ExecuteAsObject_cumbomain(string sp, object ps = null) => ExecuteAsObject<cumbomain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<cumbomainDetails> ExecuteAsList_cumbomainDetails(string sp, object ps = null) => ExecuteAsList<cumbomainDetails>(sp, ToColl(ps)); public cumbomainDetails ExecuteAsObject_cumbomainDetails(string sp, object ps = null) => ExecuteAsObject<cumbomainDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<customerBilling> ExecuteAsList_customerBilling(string sp, object ps = null) => ExecuteAsList<customerBilling>(sp, ToColl(ps)); public customerBilling ExecuteAsObject_customerBilling(string sp, object ps = null) => ExecuteAsObject<customerBilling>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<dailyreport> ExecuteAsList_dailyreport(string sp, object ps = null) => ExecuteAsList<dailyreport>(sp, ToColl(ps)); public dailyreport ExecuteAsObject_dailyreport(string sp, object ps = null) => ExecuteAsObject<dailyreport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<dailyreports> ExecuteAsList_dailyreports(string sp, object ps = null) => ExecuteAsList<dailyreports>(sp, ToColl(ps)); public dailyreports ExecuteAsObject_dailyreports(string sp, object ps = null) => ExecuteAsObject<dailyreports>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<extraItem> ExecuteAsList_extraItem(string sp, object ps = null) => ExecuteAsList<extraItem>(sp, ToColl(ps)); public extraItem ExecuteAsObject_extraItem(string sp, object ps = null) => ExecuteAsObject<extraItem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<fiscalyear> ExecuteAsList_fiscalyear(string sp, object ps = null) => ExecuteAsList<fiscalyear>(sp, ToColl(ps)); public fiscalyear ExecuteAsObject_fiscalyear(string sp, object ps = null) => ExecuteAsObject<fiscalyear>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<flatorperdiscount> ExecuteAsList_flatorperdiscount(string sp, object ps = null) => ExecuteAsList<flatorperdiscount>(sp, ToColl(ps)); public flatorperdiscount ExecuteAsObject_flatorperdiscount(string sp, object ps = null) => ExecuteAsObject<flatorperdiscount>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<goodReceiveDetails> ExecuteAsList_goodReceiveDetails(string sp, object ps = null) => ExecuteAsList<goodReceiveDetails>(sp, ToColl(ps)); public goodReceiveDetails ExecuteAsObject_goodReceiveDetails(string sp, object ps = null) => ExecuteAsObject<goodReceiveDetails>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<goodsReceiveMain> ExecuteAsList_goodsReceiveMain(string sp, object ps = null) => ExecuteAsList<goodsReceiveMain>(sp, ToColl(ps)); public goodsReceiveMain ExecuteAsObject_goodsReceiveMain(string sp, object ps = null) => ExecuteAsObject<goodsReceiveMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<issueMain> ExecuteAsList_issueMain(string sp, object ps = null) => ExecuteAsList<issueMain>(sp, ToColl(ps)); public issueMain ExecuteAsObject_issueMain(string sp, object ps = null) => ExecuteAsObject<issueMain>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<itemRate> ExecuteAsList_itemRate(string sp, object ps = null) => ExecuteAsList<itemRate>(sp, ToColl(ps)); public itemRate ExecuteAsObject_itemRate(string sp, object ps = null) => ExecuteAsObject<itemRate>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<itemWithUnit> ExecuteAsList_itemWithUnit(string sp, object ps = null) => ExecuteAsList<itemWithUnit>(sp, ToColl(ps)); public itemWithUnit ExecuteAsObject_itemWithUnit(string sp, object ps = null) => ExecuteAsObject<itemWithUnit>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<itemsales> ExecuteAsList_itemsales(string sp, object ps = null) => ExecuteAsList<itemsales>(sp, ToColl(ps)); public itemsales ExecuteAsObject_itemsales(string sp, object ps = null) => ExecuteAsObject<itemsales>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<modalAccountGroup> ExecuteAsList_modalAccountGroup(string sp, object ps = null) => ExecuteAsList<modalAccountGroup>(sp, ToColl(ps)); public modalAccountGroup ExecuteAsObject_modalAccountGroup(string sp, object ps = null) => ExecuteAsObject<modalAccountGroup>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<modalAccountSubGroup> ExecuteAsList_modalAccountSubGroup(string sp, object ps = null) => ExecuteAsList<modalAccountSubGroup>(sp, ToColl(ps)); public modalAccountSubGroup ExecuteAsObject_modalAccountSubGroup(string sp, object ps = null) => ExecuteAsObject<modalAccountSubGroup>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<ordertype> ExecuteAsList_ordertype(string sp, object ps = null) => ExecuteAsList<ordertype>(sp, ToColl(ps)); public ordertype ExecuteAsObject_ordertype(string sp, object ps = null) => ExecuteAsObject<ordertype>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<providersReport> ExecuteAsList_providersReport(string sp, object ps = null) => ExecuteAsList<providersReport>(sp, ToColl(ps)); public providersReport ExecuteAsObject_providersReport(string sp, object ps = null) => ExecuteAsObject<providersReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<purchaseMains> ExecuteAsList_purchaseMains(string sp, object ps = null) => ExecuteAsList<purchaseMains>(sp, ToColl(ps)); public purchaseMains ExecuteAsObject_purchaseMains(string sp, object ps = null) => ExecuteAsObject<purchaseMains>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<restroTable> ExecuteAsList_restroTable(string sp, object ps = null) => ExecuteAsList<restroTable>(sp, ToColl(ps)); public restroTable ExecuteAsObject_restroTable(string sp, object ps = null) => ExecuteAsObject<restroTable>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<roistore> ExecuteAsList_roistore(string sp, object ps = null) => ExecuteAsList<roistore>(sp, ToColl(ps)); public roistore ExecuteAsObject_roistore(string sp, object ps = null) => ExecuteAsObject<roistore>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<salesSummary> ExecuteAsList_salesSummary(string sp, object ps = null) => ExecuteAsList<salesSummary>(sp, ToColl(ps)); public salesSummary ExecuteAsObject_salesSummary(string sp, object ps = null) => ExecuteAsObject<salesSummary>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<salesSummaryByProviderMode> ExecuteAsList_salesSummaryByProviderMode(string sp, object ps = null) => ExecuteAsList<salesSummaryByProviderMode>(sp, ToColl(ps)); public salesSummaryByProviderMode ExecuteAsObject_salesSummaryByProviderMode(string sp, object ps = null) => ExecuteAsObject<salesSummaryByProviderMode>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<stockReport> ExecuteAsList_stockReport(string sp, object ps = null) => ExecuteAsList<stockReport>(sp, ToColl(ps)); public stockReport ExecuteAsObject_stockReport(string sp, object ps = null) => ExecuteAsObject<stockReport>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<top6Item> ExecuteAsList_top6Item(string sp, object ps = null) => ExecuteAsList<top6Item>(sp, ToColl(ps)); public top6Item ExecuteAsObject_top6Item(string sp, object ps = null) => ExecuteAsObject<top6Item>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<top6Table> ExecuteAsList_top6Table(string sp, object ps = null) => ExecuteAsList<top6Table>(sp, ToColl(ps)); public top6Table ExecuteAsObject_top6Table(string sp, object ps = null) => ExecuteAsObject<top6Table>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<unitclassforitem> ExecuteAsList_unitclassforitem(string sp, object ps = null) => ExecuteAsList<unitclassforitem>(sp, ToColl(ps)); public unitclassforitem ExecuteAsObject_unitclassforitem(string sp, object ps = null) => ExecuteAsObject<unitclassforitem>(sp, ToColl(ps)); }
public partial class SQLHandler { public List<usedBillingTermInfo> ExecuteAsList_usedBillingTermInfo(string sp, object ps = null) => ExecuteAsList<usedBillingTermInfo>(sp, ToColl(ps)); public usedBillingTermInfo ExecuteAsObject_usedBillingTermInfo(string sp, object ps = null) => ExecuteAsObject<usedBillingTermInfo>(sp, ToColl(ps)); }
public partial class SQLHandler { public DataSet ExecuteAsDataSet(string sp, object ps) => ExecuteAsDataSet(sp, ToColl(ps)); public object ExecuteAsScalar(string sp, object ps) => ExecuteAsScalar(sp, ToColl(ps)); public int ExecuteNonQuery(string sp, object ps) => ExecuteNonQuery(sp, ToColl(ps)); }
public partial class SQLHandler { public int ExecuteAsScalar_int(string sp, object ps = null) => Convert.ToInt32(ExecuteAsScalar(sp, ToColl(ps)) ?? 0); public string ExecuteAsScalar_string(string sp, object ps = null) => Convert.ToString(ExecuteAsScalar(sp, ToColl(ps))); public object ExecuteAsScalar_object(string sp, object ps = null) => ExecuteAsScalar(sp, ToColl(ps)); }
}
