
CREATE TABLE [dbo].[CDN](
	[URLID] [int] IDENTITY(1,1) NOT NULL,
	[URL] [nvarchar](500) NULL,
	[IsJS] [bit] NULL,
	[URLOrder] [int] NULL,
	[PortalID] [int] NULL,
 CONSTRAINT [PK_CDN] PRIMARY KEY CLUSTERED 
(
	[URLID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


