
CREATE TABLE [dbo].[L_LaundryRate](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ClothTypeID] [int] NULL,
	[LaundryTypeID] [int] NULL,
	[Rate] [decimal](18, 0) NULL,
 CONSTRAINT [PK_L_LaundryRate] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
