

CREATE TABLE [dbo].[RO_GoodsReceivedDetls](
	[GDId] [int] IDENTITY(1,1) NOT NULL,
	[GMId] [int] NOT NULL,
	[PDId] [int] NOT NULL,
	[Qnty] [bigint] NOT NULL,
	[STId] [int] NULL,
 CONSTRAINT [PK_GoodsReceivedDetls] PRIMARY KEY CLUSTERED 
(
	[GDId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


