

CREATE TABLE [dbo].[RO_GoodsReceivedMain](
	[GMId] [int] IDENTITY(1,1) NOT NULL,
	[GMNo] [varchar](200) NOT NULL,
	[STId] [int] NOT NULL,
	[PostedBy] [varchar](200) NOT NULL,
	[PostedOn] [datetime] NOT NULL,
 CONSTRAINT [PK_GoodsReceived] PRIMARY KEY CLUSTERED 
(
	[GMId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


