

CREATE TABLE [dbo].[RO_ItemStatus](
	[StatusID] [int] IDENTITY(1,1) NOT NULL,
	[ItemStatus] [varchar](50) NULL,
 CONSTRAINT [PK_RO_ItemStatus] PRIMARY KEY CLUSTERED 
(
	[StatusID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


