

CREATE TABLE [dbo].[RO_SalesBillTermMaster](
	[SBTMasterId] [int] IDENTITY(1,1) NOT NULL,
	[SalesMasterId] [int] NULL,
 CONSTRAINT [PK_RO_SalesReportMaster] PRIMARY KEY CLUSTERED 
(
	[SBTMasterId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


