

CREATE TABLE [dbo].[RO_SPM](
	[SPMID] [int] IDENTITY(1,1) NOT NULL,
	[SPMNames] [nchar](10) NULL,
 CONSTRAINT [PK_RO_SPM] PRIMARY KEY CLUSTERED 
(
	[SPMID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


