

CREATE TABLE [dbo].[ROI_AdjustmentMain](
	[AMId] [int] IDENTITY(1,1) NOT NULL,
	[AMNo] [nvarchar](50) NOT NULL,
	[STId] [int] NOT NULL,
	[Remarks] [varchar](500) NOT NULL,
	[FYId] [nvarchar](50) NOT NULL,
	[PostedOn] [datetime] NOT NULL,
	[PostedBy] [varchar](128) NOT NULL,
 CONSTRAINT [PK_AdjustmentMain] PRIMARY KEY CLUSTERED 
(
	[AMId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


