

CREATE TABLE [dbo].[ROI_AdjustmentDetls](
	[ADId] [int] IDENTITY(1,1) NOT NULL,
	[AMId] [int] NOT NULL,
	[ITId] [int] NOT NULL,
	[UsedUnitId] [int] NOT NULL,
	[Qnty] [bigint] NOT NULL,
	[QntyInText] [varchar](250) NOT NULL,
	[AdType] [int] NOT NULL,
	[PDId] [int] NOT NULL CONSTRAINT [DF_AdjustmentDetls_PDId]  DEFAULT ((0)),
 CONSTRAINT [PK_AdjustmentDetls] PRIMARY KEY CLUSTERED 
(
	[ADId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO


ALTER TABLE ROI_AdjustmentDetls ADD IsAdd BIT


