
CREATE TABLE [dbo].[ScheduleWeek](
	[ScheduleID] [int] NOT NULL,
	[WeekDayID] [int] NOT NULL,
	[ID] [int] IDENTITY(1,1) NOT NULL,
 CONSTRAINT [PK_ScheduleWeek] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

ALTER TABLE [dbo].[ScheduleWeek]  WITH CHECK ADD  CONSTRAINT [FK_ScheduleWeek_Schedule] FOREIGN KEY([ScheduleID])
REFERENCES [dbo].[Schedule] ([ScheduleID])
GO

ALTER TABLE [dbo].[ScheduleWeek] CHECK CONSTRAINT [FK_ScheduleWeek_Schedule]
GO


