
CREATE TABLE [dbo].[tbl_ROVaultNote](
	[NoteID] [int] IDENTITY(1,1) NOT NULL,
	[Note] [int] NULL,
	[IsCoin] [bit] NULL,
 CONSTRAINT [PK_tbl_Note] PRIMARY KEY CLUSTERED 
(
	[NoteID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO


