SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_GoodsReceivedDetls](
	[GDId] [int] IDENTITY(1,1) NOT NULL,
	[GMId] [int] NOT NULL,
	[PDId] [int] NOT NULL,
	[Qnty] [decimal](18, 2) NOT NULL,
	[STId] [int] NULL,
	[Rate] [decimal](18, 2) NULL,
	[Total] [decimal](18, 2) NULL,
	[Discount] [decimal](10, 2) NULL,
	[IsVat] [bit] NULL,
 CONSTRAINT [PK_GoodsReceivedDetls] PRIMARY KEY CLUSTERED 
(
	[GDId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
