SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ac_MergeDetails](
	[MergeId] [int] IDENTITY(1,1) NOT NULL,
	[MergeNewAccId] [int] NOT NULL,
	[MergeOneAccId] [int] NOT NULL,
	[MergeTwoAccId] [int] NOT NULL,
	[MergedOn] [datetime] NOT NULL,
	[MergedBy] [nvarchar](50) NOT NULL,
 CONSTRAINT [PK_Ac_MergeDetails] PRIMARY KEY CLUSTERED 
(
	[MergeId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
