SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DailyChalanIssueDetails](
	[issueID] [int] IDENTITY(1,1) NOT NULL,
	[IssuedBy] [nvarchar](256) NOT NULL,
	[IssuedAmount] [decimal](18, 2) NOT NULL,
	[For] [nvarchar](256) NOT NULL,
	[DailyChalanId] [int] NOT NULL,
 CONSTRAINT [PK_DailyChalanIssueDetails] PRIMARY KEY CLUSTERED 
(
	[issueID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
