SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ac_VoucherCount](
	[VoucherCountId] [int] IDENTITY(1,1) NOT NULL,
	[VoucherTypeId] [int] NULL,
	[FiscalYearId] [int] NULL,
	[VoucherCount] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[VoucherCountId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
