SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ScheduleDay](
	[ScheduleID] [int] NOT NULL,
	[DayID] [int] NOT NULL,
 CONSTRAINT [PK_ScheduleDay] PRIMARY KEY CLUSTERED 
(
	[ScheduleID] ASC,
	[DayID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ScheduleDay]  WITH CHECK ADD  CONSTRAINT [FK_ScheduleDay_Schedule] FOREIGN KEY([ScheduleID])
REFERENCES [dbo].[Schedule] ([ScheduleID])
GO
ALTER TABLE [dbo].[ScheduleDay] CHECK CONSTRAINT [FK_ScheduleDay_Schedule]
GO
