SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROI_ITEMBal](
	[ItemBalID] [int] IDENTITY(1,1) NOT NULL,
	[ITId] [int] NOT NULL,
	[PDId] [int] NULL,
	[STId] [int] NOT NULL,
	[OPBal] [bigint] NOT NULL,
	[CLBal] [decimal](18, 2) NOT NULL,
	[PostedDate] [datetime] NOT NULL,
	[OPRate] [decimal](18, 6) NULL,
	[CLRate] [decimal](18, 6) NULL,
	[TotalValue] [decimal](22, 6) NULL,
 CONSTRAINT [PK_ROI_ITEMBal] PRIMARY KEY CLUSTERED 
(
	[ItemBalID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[ROI_ITEMBal] ADD  CONSTRAINT [DF_ROI_ITEMBal_OPBal]  DEFAULT ((0)) FOR [OPBal]
GO
ALTER TABLE [dbo].[ROI_ITEMBal] ADD  CONSTRAINT [DF_ROI_ITEMBal_CLBal]  DEFAULT ((0)) FOR [CLBal]
GO
ALTER TABLE [dbo].[ROI_ITEMBal] ADD  CONSTRAINT [DF_ROI_ITEMBal_PostedDate]  DEFAULT (getdate()) FOR [PostedDate]
GO
