SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_restroTable](
	[restrotableId] [int] IDENTITY(1,1) NOT NULL,
	[restrotableTitle] [varchar](128) NOT NULL,
	[restroRoomId] [int] NULL,
	[restrotablesStatusID] [int] NULL,
	[Seatcap] [int] NULL,
	[IsTable] [bit] NULL,
	[Rate] [decimal](18, 2) NULL,
 CONSTRAINT [PK__RO_restr__4A58D9675911273F] PRIMARY KEY CLUSTERED 
(
	[restrotableId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_RO_restroTable_restrotableId] ON [dbo].[RO_restroTable]
(
	[restrotableId] ASC
)
INCLUDE([restroRoomId],[restrotableTitle]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
