SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_RestroRoom](
	[restroRoomId] [int] IDENTITY(1,1) NOT NULL,
	[restroRoom] [nvarchar](50) NULL,
	[RoomTypeID] [int] NULL,
	[RoomStatusId] [int] NULL,
 CONSTRAINT [PK_RO_RestroRoom] PRIMARY KEY CLUSTERED 
(
	[restroRoomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_RO_RestroRoom_restroRoomId] ON [dbo].[RO_RestroRoom]
(
	[restroRoomId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
