SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Comp_ExtraItem](
	[ExtraOrderID] [int] IDENTITY(1,1) NOT NULL,
	[CompMasterID] [int] NULL,
	[CompId] [int] NULL,
	[ItemID] [int] NULL,
	[ExtraItemID] [int] NULL,
	[ExtraItem] [nvarchar](256) NULL,
	[Quantity] [int] NULL,
	[ExtraPrice] [decimal](18, 2) NULL,
 CONSTRAINT [PK_Comp_ExtraItem] PRIMARY KEY CLUSTERED 
(
	[ExtraOrderID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
