SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_CakeOrderToken](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[OrderMasterID] [int] NULL,
	[CustomerID] [int] NULL,
	[CustomerName] [nvarchar](50) NULL,
	[Phone] [nvarchar](50) NULL,
	[TokenNo] [int] NULL,
	[AddedBy] [datetime] NULL,
	[Address] [nvarchar](150) NULL,
 CONSTRAINT [PK_RO_Cake_Token] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
