SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[WaiterNotificationLog](
	[PushNotificationId] [int] IDENTITY(1,1) NOT NULL,
	[WaiterName] [nvarchar](max) NULL,
	[WaiterIP] [nvarchar](max) NULL,
	[WaiterLoginDateTime] [datetime] NULL,
 CONSTRAINT [PK_WaiterNotificationLog] PRIMARY KEY CLUSTERED 
(
	[PushNotificationId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
