SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_ReservedTable](
	[ReservedID] [int] IDENTITY(1,1) NOT NULL,
	[ReservationID] [int] NULL,
	[TableID] [int] NULL,
 CONSTRAINT [PK_RO_ReservedTable] PRIMARY KEY CLUSTERED 
(
	[ReservedID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
