SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_AdvancePaymentMode](
	[AdvancePaymentID] [int] IDENTITY(1,1) NOT NULL,
	[RoomBookDetailsId] [int] NULL,
	[VoucherNo] [nvarchar](256) NULL,
	[PaymentModeID] [int] NULL,
	[ProviderID] [int] NULL,
	[TransactionNo] [nvarchar](256) NULL,
	[PayAmount] [decimal](18, 2) NULL,
	[TransactionID] [int] NULL,
	[SettlementAmount] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[AdvancePaymentID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY],
 CONSTRAINT [IX_RO_AdvancePaymentMode] UNIQUE NONCLUSTERED 
(
	[RoomBookDetailsId] ASC,
	[PaymentModeID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
