SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_ProductionMain](
	[ProductionMainId] [int] IDENTITY(1,1) NOT NULL,
	[ItemId] [int] NULL,
	[UnitId] [int] NULL,
	[StoreId] [int] NULL,
	[Quantity] [decimal](18, 2) NULL,
	[AddedOn] [datetime] NULL,
	[AddedBy] [varchar](50) NULL,
 CONSTRAINT [PK_RO_ProductionMain] PRIMARY KEY CLUSTERED 
(
	[ProductionMainId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
