SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LayoutMgr](
	[ID] [int] IDENTITY(1,1) NOT NULL,
	[ModuleOrder] [nvarchar](100) NOT NULL,
	[PortelID] [int] NULL,
	[ModuleID] [nvarchar](100) NULL,
	[ModuleName] [nvarchar](100) NULL,
	[PaneName] [nvarchar](100) NULL,
 CONSTRAINT [PK_LayoutMgr] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
