SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[H_LostAndFound](
	[LF_ID] [int] IDENTITY(1,1) NOT NULL,
	[RoomType] [nvarchar](250) NULL,
	[Room] [nvarchar](150) NULL,
	[Date] [nvarchar](max) NULL,
	[Guest_Name] [nvarchar](250) NULL,
	[Type] [nvarchar](50) NULL,
	[Item_Name] [nvarchar](500) NULL,
 CONSTRAINT [PK_H_LostAndFound] PRIMARY KEY CLUSTERED 
(
	[LF_ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
