SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_ProductionDetails](
	[ProductionDetailsId] [int] IDENTITY(1,1) NOT NULL,
	[ProductionMainID] [int] NULL,
	[ItemId] [int] NULL,
	[ItemUnitId] [int] NULL,
	[Quantity] [decimal](18, 2) NULL,
	[StoreID] [int] NULL,
 CONSTRAINT [PK_RO_ProductionDetails] PRIMARY KEY CLUSTERED 
(
	[ProductionDetailsId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
