SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_BillingAmount](
	[BAID] [int] IDENTITY(1,1) NOT NULL,
	[BilingID] [int] NULL,
	[SalesMasterID] [int] NULL,
	[Amount] [decimal](18, 2) NULL,
	[IsVoid] [bit] NULL,
	[rate] [decimal](18, 2) NULL,
 CONSTRAINT [PK_RO_BillingAmount] PRIMARY KEY CLUSTERED 
(
	[BAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_RO_BillingAmount_SalesMasterID_BilingID] ON [dbo].[RO_BillingAmount]
(
	[SalesMasterID] ASC,
	[BilingID] ASC
)
INCLUDE([Amount]) WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RO_BillingAmount] ADD  CONSTRAINT [DF_RO_BillingAmount_IsVoid]  DEFAULT ((0)) FOR [IsVoid]
GO
