SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_SMS_Message](
	[smsID] [int] IDENTITY(1,1) NOT NULL,
	[mobileNum] [nvarchar](50) NULL,
	[message] [nvarchar](max) NULL,
	[sentDate] [datetime] NULL,
 CONSTRAINT [PK_RO_SMS_Message] PRIMARY KEY CLUSTERED 
(
	[smsID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
