SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROI_SalesStockTransaction](
	[SalesTranId] [int] IDENTITY(1,1) NOT NULL,
	[SalesDetailId] [int] NULL,
	[StoreId] [int] NULL,
	[ItemId] [int] NULL,
	[SalesQty] [decimal](18, 2) NULL,
	[SalesUnit] [int] NULL,
	[SalesRate] [decimal](18, 2) NULL,
	[SalesAmt] [decimal](18, 2) NULL,
	[TransactionDate] [datetime] NULL,
 CONSTRAINT [PK__ROI_Sale__B92123E627000699] PRIMARY KEY CLUSTERED 
(
	[SalesTranId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_ROI_SalesStockTransaction_SalesDetailId] ON [dbo].[ROI_SalesStockTransaction]
(
	[SalesDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
