SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Req_IssueLog](
	[LogId] [int] IDENTITY(1,1) NOT NULL,
	[RecqDetailId] [int] NULL,
	[IssueMainId] [int] NULL,
	[IssuedOn] [datetime] NULL,
	[IssuedBy] [nvarchar](256) NULL,
	[IssuedQuantity] [decimal](18, 2) NULL,
PRIMARY KEY CLUSTERED 
(
	[LogId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
