SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[ROI_IssueDetails](
	[IDId] [int] IDENTITY(1,1) NOT NULL,
	[IMId] [int] NOT NULL,
	[ITID] [int] NOT NULL,
	[UsedUnitId] [int] NOT NULL,
	[QntyInText] [varchar](250) NOT NULL,
	[ReceivedBy] [varchar](250) NULL,
	[ReceivedOn] [datetime] NULL,
	[Qnty] [decimal](18, 2) NULL,
 CONSTRAINT [PK_IssueDetails] PRIMARY KEY CLUSTERED 
(
	[IDId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
