SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DanfeServiceLogs](
	[Id] [bigint] IDENTITY(1,1) NOT NULL,
	[TenantCode] [nvarchar](100) NOT NULL,
	[LogTime] [datetime] NOT NULL,
	[Module] [nvarchar](100) NOT NULL,
	[Action] [nvarchar](100) NOT NULL,
	[Status] [nvarchar](20) NOT NULL,
	[FullDetails] [nvarchar](max) NOT NULL,
	[DedupeKey] [nvarchar](200) NULL,
	[ApiKey] [nvarchar](100) NULL,
	[LogFor] [nvarchar](200) NULL,
	[LogDetails] [nvarchar](max) NULL,
	[CreatedAtUtc] [datetime2](7) NULL,
	[PostedToApi] [bit] NOT NULL,
	[DeduplicationHash] [nvarchar](64) NULL,
PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_DanfeServiceLogs_DedupHash] ON [dbo].[DanfeServiceLogs]
(
	[DeduplicationHash] ASC
)
WHERE ([DeduplicationHash] IS NOT NULL)
WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_DanfeServiceLogs_Module_Status] ON [dbo].[DanfeServiceLogs]
(
	[Module] ASC,
	[Status] ASC,
	[LogTime] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
CREATE NONCLUSTERED INDEX [IX_DanfeServiceLogs_Posted] ON [dbo].[DanfeServiceLogs]
(
	[PostedToApi] ASC,
	[CreatedAtUtc] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_DanfeServiceLogs_Tenant_Dedupe] ON [dbo].[DanfeServiceLogs]
(
	[TenantCode] ASC,
	[DedupeKey] ASC,
	[LogTime] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
SET ANSI_PADDING ON

GO
CREATE NONCLUSTERED INDEX [IX_DanfeServiceLogs_TenantCode_LogTime] ON [dbo].[DanfeServiceLogs]
(
	[TenantCode] ASC,
	[LogTime] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DanfeServiceLogs] ADD  DEFAULT (getdate()) FOR [LogTime]
GO
ALTER TABLE [dbo].[DanfeServiceLogs] ADD  CONSTRAINT [DF_DanfeServiceLogs_PostedToApi]  DEFAULT ((0)) FOR [PostedToApi]
GO
