SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[StoreItemMinimumStock](
	[StoreItemId] [int] IDENTITY(1,1) NOT NULL,
	[ItemId] [int] NULL,
	[StoreId] [int] NULL,
	[Unit] [int] NULL,
	[Value] [int] NULL,
	[AddedOn] [date] NULL,
 CONSTRAINT [PK_StoreItemMinimumStock] PRIMARY KEY CLUSTERED 
(
	[StoreItemId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
