SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_CAKE_BillingAmount](
	[BAID] [int] IDENTITY(1,1) NOT NULL,
	[BilingID] [int] NULL,
	[SalesMasterID] [int] NULL,
	[Amount] [decimal](18, 2) NULL,
	[IsVoid] [bit] NULL,
	[rate] [decimal](18, 2) NULL,
	[SalesType] [nvarchar](30) NULL,
 CONSTRAINT [PK_RO_CAKE_BillingAmount] PRIMARY KEY CLUSTERED 
(
	[BAID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[RO_CAKE_BillingAmount] ADD  DEFAULT ((0)) FOR [IsVoid]
GO
