SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Req_RecquistionDetails](
	[RecqDetailId] [int] IDENTITY(1,1) NOT NULL,
	[RecqId] [int] NULL,
	[ItemId] [int] NULL,
	[Quantity] [decimal](18, 2) NULL,
	[Unit] [int] NULL,
	[IssuedQuantity] [decimal](18, 2) NULL,
	[StatusId] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[RecqDetailId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
