SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[RO_Categories](
	[CategoriesID] [int] IDENTITY(1,1) NOT NULL,
	[MenuID] [int] NOT NULL,
	[CategoriesName] [varchar](128) NULL,
	[PhotoPath] [varchar](128) NULL,
 CONSTRAINT [PK_RO_Categories] PRIMARY KEY CLUSTERED 
(
	[CategoriesID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
CREATE NONCLUSTERED INDEX [IX_FK_RO_Categories_RO_Items] ON [dbo].[RO_Categories]
(
	[MenuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
GO
ALTER TABLE [dbo].[RO_Categories]  WITH CHECK ADD  CONSTRAINT [FK_RO_Categories_RO_Menus] FOREIGN KEY([MenuID])
REFERENCES [dbo].[RO_Menus] ([MenuID])
GO
ALTER TABLE [dbo].[RO_Categories] CHECK CONSTRAINT [FK_RO_Categories_RO_Menus]
GO
