SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PageMenu](
	[PageMenuID] [int] IDENTITY(1,1) NOT NULL,
	[PageID] [int] NULL,
	[PortalID] [int] NULL,
	[IsAdmin] [bit] NULL,
	[IsFooter] [bit] NULL,
	[ShowInMenu] [bit] NULL,
 CONSTRAINT [PK_PageMenu] PRIMARY KEY CLUSTERED 
(
	[PageMenuID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]

GO
ALTER TABLE [dbo].[PageMenu] ADD  CONSTRAINT [DF_PageMenu_ShowInMenu]  DEFAULT ((1)) FOR [ShowInMenu]
GO
