#!/usr/bin/env python3
"""Mechanically ports the legacy .asmx service bodies into compilable C# (no logic edits).
Usage: python3 tools/port_asmx.py <legacy-repo-root> <out-dir>"""
import re, sys, os
root, out = sys.argv[1], sys.argv[2]
SRC = [
  ("Services/OrderWebService.asmx",                                     "OrderWebService",        None),
  ("Services/RestroWebService.asmx",                                    "RestroWebService",       None),
  ("Modules/ROUSER/ROLoginWebService.asmx",                             "RoLoginWebService",      "RoWebService"),
  ("Modules/RestroDashboard/services/DashBoardWebService.asmx",         "DashBoardWebService",    None),
  ("Modules/ROPurchaseOrder/ROPurchaseOrderWebService.asmx",            "RoPurchaseOrderWebService","RoWebService"),
]
DROP_USING = ("System.Web.Mvc","TheArtOfDev","iTextSharp","System.Drawing","SageFrame.Common","System.Data.SqlClient","System.Diagnostics","System.Web.Services.Protocols","System.Configuration","Hangfire","RptReportViewer","Microsoft.Reporting")
os.makedirs(out, exist_ok=True)
for rel, newname, oldclass in SRC:
    txt = open(os.path.join(root, "SageFrame", rel), encoding="utf-8-sig", errors="replace").read().replace("\r", "")
    txt = re.sub(r'<%@.*?%>[ \t]*\n?', '', txt, count=1, flags=re.S)
    cls = oldclass or newname
    if oldclass:
        txt = re.sub(r'\b%s\b' % oldclass, newname, txt)
    lines = [l for l in txt.split("\n") if not (l.startswith("using ") and any(d in l for d in DROP_USING))]
    body = "\n".join(lines)
    hdr = "// <auto-generated> Ported verbatim from SageFrame/%s by tools/port_asmx.py. Do not hand-edit; re-run the tool. </auto-generated>\n#pragma warning disable\n" % rel
    open(os.path.join(out, newname + ".cs"), "w", encoding="utf-8").write(hdr + body + "\n")
    print("ported", rel, "->", newname + ".cs", len(lines), "lines")
